apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-search-backend-module-announcements
  namespace: rhdh
  title: "Search Backend Module Announcements"
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://github.com/backstage/community-plugins/issues
    title: Bugs
  - title: Source Code
    url: https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  tags: []
spec:
  packageName: '@backstage-community/plugin-search-backend-module-announcements'
  dynamicArtifact: oci://quay.io/veecode/backstage-community-plugin-search-backend-module-announcements:bs_1.48.4__0.10.0!backstage-community-plugin-search-backend-module-announcements
  version: 0.10.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.48.4
  author: VeeCode
  support: community
  lifecycle: active
  partOf:
  - announcements
