apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator-form-widgets
  namespace: rhdh
  title: "Orchestrator Form Widgets"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-form-widgets
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-form-widgets
  tags:
    - automation
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-orchestrator-form-widgets"
  # Tag: 1.9.4--1.6.9, Build date: 2026-04-30T18:56:56Z
  dynamicArtifact: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:70fe997519010e9cb570249f609ae22771b85a9813767fe7ad7818a2aac82a3e"
  version: 1.6.9
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - orchestrator
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: { }
