apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator-form-widgets
  namespace: rhdh
  title: "Orchestrator Form Widgets"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-form-widgets
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-form-widgets
  tags:
    - automation
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-orchestrator-form-widgets"
  # Tag: 1.10--1.10.7, Build date: 2026-06-06T02:23:39Z
  dynamicArtifact: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:3aaa68b7b7d1900baee3514e43add958b642e243a984a1a5dfd73c9dd2767119"
  version: 1.10.7
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - orchestrator
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: {}
