workspace/3scale:
  - 'Workspace\\s*3scale'

workspace/acr:
  - 'Workspace\\s*acr'

workspace/acs:
  - 'Workspace\\s*acs'

workspace/adoption-insights:
  - 'Workspace\\s*adoption-insights'

workspace/adr:
  - 'Workspace\\s*adr'

workspace/ai-integrations:
  - 'Workspace\\s*ai-integrations'

workspace/analytics:
  - 'Workspace\\s*analytics'

workspace/announcements:
  - 'Workspace\\s*announcements'

workspace/apiconnect:
  - 'Workspace\\s*apiconnect'

workspace/argocd:
  - 'Workspace\\s*argocd'

workspace/aws-codebuild:
  - 'Workspace\\s*aws-codebuild'

workspace/aws-ecs:
  - 'Workspace\\s*aws-ecs'

workspace/azure-devops:
  - 'Workspace\\s*azure-devops'

workspace/backstage:
  - 'Workspace\\s*backstage'

workspace/bookmarks:
  - 'Workspace\\s*bookmarks'

workspace/bulk-import:
  - 'Workspace\\s*bulk-import'

workspace/config-viewer:
  - 'Workspace\\s*config-viewer'

workspace/cost-management:
  - 'Workspace\\s*cost-management'

workspace/dynatrace:
  - 'Workspace\\s*dynatrace'

workspace/dynatrace-dql:
  - 'Workspace\\s*dynatrace-dql'

workspace/env-viewer:
  - 'Workspace\\s*env-viewer'

workspace/extensions:
  - 'Workspace\\s*extensions'

workspace/github-actions:
  - 'Workspace\\s*github-actions'

workspace/github-issues:
  - 'Workspace\\s*github-issues'

workspace/github-notifications:
  - 'Workspace\\s*github-notifications'

workspace/github-pull-requests-board:
  - 'Workspace\\s*github-pull-requests-board'

workspace/gitlab:
  - 'Workspace\\s*gitlab'

workspace/global-floating-action-button:
  - 'Workspace\\s*global-floating-action-button'

workspace/global-header:
  - 'Workspace\\s*global-header'

workspace/homepage:
  - 'Workspace\\s*homepage'

workspace/icon-viewer:
  - 'Workspace\\s*icon-viewer'

workspace/jenkins:
  - 'Workspace\\s*jenkins'

workspace/jfrog-artifactory:
  - 'Workspace\\s*jfrog-artifactory'

workspace/keycloak:
  - 'Workspace\\s*keycloak'

workspace/kiali:
  - 'Workspace\\s*kiali'

workspace/konflux:
  - 'Workspace\\s*konflux'

workspace/lighthouse:
  - 'Workspace\\s*lighthouse'

workspace/lightspeed:
  - 'Workspace\\s*lightspeed'

workspace/mcp-chat:
  - 'Workspace\\s*mcp-chat'

workspace/mcp-integrations:
  - 'Workspace\\s*mcp-integrations'

workspace/mta:
  - 'Workspace\\s*mta'

workspace/nexus-repository-manager:
  - 'Workspace\\s*nexus-repository-manager'

workspace/npm:
  - 'Workspace\\s*npm'

workspace/orchestrator:
  - 'Workspace\\s*orchestrator'

workspace/pagerduty:
  - 'Workspace\\s*pagerduty'

workspace/pingidentity:
  - 'Workspace\\s*pingidentity'

workspace/quay:
  - 'Workspace\\s*quay'

workspace/quickstart:
  - 'Workspace\\s*quickstart'

workspace/rbac:
  - 'Workspace\\s*rbac'

workspace/roadie-backstage-plugins:
  - 'Workspace\\s*roadie-backstage-plugins'

workspace/scaffolder-backend-module-kubernetes:
  - 'Workspace\\s*scaffolder-backend-module-kubernetes'

workspace/scaffolder-backend-module-regex:  
- 'Workspace\\s*scaffolder-backend-module-regex'

workspace/scaffolder-backend-module-servicenow:
  - 'Workspace\\s*scaffolder-backend-module-servicenow'

workspace/scaffolder-backend-module-sonarqube:
  - 'Workspace\\s*scaffolder-backend-module-sonarqube'

workspace/scaffolder-relation-processor:
  - 'Workspace\\s*scaffolder-relation-processor'

workspace/scorecard:
  - 'Workspace\\s*scorecard'

workspace/servicenow:
  - 'Workspace\\s*servicenow'

workspace/sonarqube:
  - 'Workspace\\s*sonarqube'

workspace/tech-insights:
  - 'Workspace\\s*tech-insights'

workspace/tech-radar:
  - 'Workspace\\s*tech-radar'

workspace/tekton:
  - 'Workspace\\s*tekton'

workspace/theme:
  - 'Workspace\\s*theme'

workspace/todo:
  - 'Workspace\\s*todo'

workspace/topology:
  - 'Workspace\\s*topology'

workspace/translations:
  - 'Workspace\\s*translations'

workspace/x2a:
  - 'Workspace\\s*x2a'
