import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const OVERLAY_UPSTREAM_REPO = 'redhat-developer/rhdh-plugin-export-overlays';
/** orchestrator yarn.lock is ~1.5 MiB; Node spawnSync default maxBuffer is 1 MiB */
const SPAWN_MAX_BUFFER = 64 * 1024 * 1024;
const PATCH_FILE = '0-cve-yarn-lock.patch';
const MANIFEST = 'cve-backports.yaml';
const LOCKFILE = 'yarn.lock';
const CVE_API = 'https://cveawg.mitre.org/api/cve/';
const CVE_ID_RE = /^CVE-\d{4}-\d+$/i;
const MANIFEST_HEADER = `# CVE backports applied via workspace patches (not repo-ref bumps).
# Auto-generated by scripts/yarnlock-backport.
# Optional: add notes on any backport row (preserved when you re-run generate).

`;

/** Absolute path under fixed system dirs (not $PATH). */
function systemBin(name: string): string {
  for (const dir of ['/usr/bin', '/bin', '/usr/local/bin', '/opt/homebrew/bin']) {
    const candidate = join(dir, name);
    if (existsSync(candidate)) return candidate;
  }
  throw new Error(`command not found: ${name}`);
}
const BIN_DIFF = systemBin('diff');
const BIN_PATCH = systemBin('patch');

type Json = Record<string, unknown>;
type VersionRange = { from: string; to: string; upper_inclusive: boolean };
type ManifestRow = { cve_ids: string[]; package: string; patch_version: string; notes?: string };
type CveDetails = { name: string; names: string[]; patch_versions: string[]; affected_ranges: VersionRange[] };
type ManifestEntry = { cveId: string; package: string; patch_versions: string[]; notes?: string };

const INCOMPARABLE_VERSIONS = new Set(['0', '*', 'N/A', 'NA']);
const AUTO_NOTE_PREFIX = '[auto] ';
const EMPTY_CVE: CveDetails = { name: '', names: [], patch_versions: [], affected_ranges: [] };

/** Coerce JSON values to string without `[object Object]` surprises. */
function asString(value: unknown): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return '';
}

// --- CVE ---

export function normalizeCveId(cveId: string): string {
  const id = cveId.trim().toUpperCase().replaceAll(' ', '');
  if (!CVE_ID_RE.test(id)) throw new Error('not a CVE id');
  return id;
}

/** Parse `CVE-…` or `CVE-…/pkg` / `CVE-…/@scope/pkg,alias`. */
export function parseCveCliToken(raw: string): [string, string[]] {
  const text = raw.trim().replaceAll(' ', '');
  if (!text) throw new Error('empty CVE token');
  const slash = text.indexOf('/');
  const cveId = normalizeCveId(slash >= 0 ? text.slice(0, slash) : text);
  const overrides = (slash >= 0 ? text.slice(slash + 1) : '')
    .split(',')
    .map(s => s.trim())
    .filter(Boolean);
  return [cveId, overrides];
}

/**
 * Split `--cve` on commas that start the next CVE id so package aliases
 * (`CVE-…/@scope/pkg,alias`) stay inside one token.
 */
export function parseCveArg(raw: string): Array<[string, string[]]> {
  const tokens = raw
    .split(/,(?=CVE-)/i)
    .map(t => t.trim())
    .filter(Boolean);
  if (!tokens.length) throw new Error('CVE list is empty');
  const seen = new Set<string>();
  const parsed: Array<[string, string[]]> = [];
  for (const token of tokens) {
    const entry = parseCveCliToken(token);
    if (seen.has(entry[0])) throw new Error('duplicate CVE in --cve list');
    seen.add(entry[0]);
    parsed.push(entry);
  }
  return parsed;
}

function unique(versions: string[]): string[] {
  return [...new Set(versions.filter(Boolean))];
}

/** Parse MITRE version text like `>=1.0.0, <2.0.0`, `<=1.2.3`, `<1.2.3`, `>=1.0.0`. */
function rangesFromVersionText(lowRaw: string): { fixes: string[]; ranges: VersionRange[] } {
  const compound = />=\s*([\w.-]+)\s*,\s*<\s*([\w.-]+)/.exec(lowRaw);
  if (compound) {
    return {
      fixes: [compound[2]],
      ranges: [{ from: compound[1], to: compound[2], upper_inclusive: false }],
    };
  }
  const lte = /^\s*<=\s*([\w.-]+)\s*$/.exec(lowRaw);
  if (lte) {
    return { fixes: [], ranges: [{ from: '0', to: lte[1], upper_inclusive: true }] };
  }
  const lt = /^\s*<\s*([\w.-]+)\s*$/.exec(lowRaw);
  if (lt) {
    return { fixes: [lt[1]], ranges: [{ from: '0', to: lt[1], upper_inclusive: false }] };
  }
  const gte = /^\s*>=\s*([\w.-]+)\s*$/.exec(lowRaw);
  if (gte) {
    return { fixes: [], ranges: [{ from: gte[1], to: '99999.0.0', upper_inclusive: true }] };
  }
  return { fixes: [], ranges: [] };
}

function versionEntryToRanges(v: Json): { fixes: string[]; ranges: VersionRange[] } {
  if (asString(v.status).toLowerCase() !== 'affected') return { fixes: [], ranges: [] };

  const lowRaw = asString(v.version).trim();
  const loDefault = lowRaw && !INCOMPARABLE_VERSIONS.has(lowRaw.toUpperCase()) ? lowRaw : '0';
  const fixes: string[] = [];
  const ranges: VersionRange[] = [];

  const lessThan = asString(v.lessThan).trim();
  if (lessThan) {
    // Exclusive upper bound ⇒ bound version is the first fixed release.
    fixes.push(lessThan);
    ranges.push({ from: loDefault, to: lessThan, upper_inclusive: false });
  }
  const lessThanOrEqual = asString(v.lessThanOrEqual).trim();
  if (lessThanOrEqual) {
    // Inclusive upper bound ⇒ bound version is still affected (not a fix).
    ranges.push({ from: loDefault, to: lessThanOrEqual, upper_inclusive: true });
  }

  if (ranges.length) return { fixes: unique(fixes), ranges };

  const fromText = rangesFromVersionText(lowRaw);
  return { fixes: unique([...fixes, ...fromText.fixes]), ranges: fromText.ranges };
}

function collectPackageCveData(affected: Json[]): { fixes: string[]; ranges: VersionRange[] } {
  const fixes: string[] = [];
  const ranges: VersionRange[] = [];
  for (const entry of affected) {
    for (const versionEntry of (entry.versions as Json[]) ?? []) {
      const parsed = versionEntryToRanges(versionEntry);
      fixes.push(...parsed.fixes);
      ranges.push(...parsed.ranges);
    }
  }
  return { fixes, ranges };
}

/** Package names + affected ranges from MITRE (or CLI overrides). Lockfile supplies installed versions. */
export function parseCveDetails(record: Json, overrideNames?: string[]): CveDetails {
  const meta = (record.cveMetadata as Json) ?? {};
  if (asString(meta.state).toUpperCase() === 'REJECTED') return EMPTY_CVE;

  const affected = (((record.containers as Json)?.cna as Json)?.affected as Json[]) ?? [];

  if (overrideNames?.length) {
    const { fixes, ranges } = collectPackageCveData(affected);
    return {
      name: overrideNames[0],
      names: [...overrideNames],
      patch_versions: unique(fixes),
      affected_ranges: ranges.filter(r => r.to),
    };
  }

  const byPackage = new Map<string, { fixes: string[]; ranges: VersionRange[] }>();
  for (const entry of affected) {
    for (const key of ['packageName', 'product', 'vendor'] as const) {
      const name = asString(entry[key]).trim();
      if (!name) continue;
      const parsed = collectPackageCveData([entry]);
      const slot = byPackage.get(name) ?? { fixes: [], ranges: [] };
      slot.fixes.push(...parsed.fixes);
      slot.ranges.push(...parsed.ranges);
      byPackage.set(name, slot);
      break;
    }
  }
  if (!byPackage.size) return EMPTY_CVE;

  const [name, slot] = [...byPackage.entries()].sort(
    (a, b) =>
      b[1].fixes.length + b[1].ranges.length - (a[1].fixes.length + a[1].ranges.length) ||
      a[0].localeCompare(b[0]),
  )[0];
  return {
    name,
    names: [name],
    patch_versions: unique(slot.fixes),
    affected_ranges: slot.ranges.filter(r => r.to),
  };
}

/** Semver-ish sort key for comparing version strings. */
export function semverSortKey(version: string): (number | string)[] {
  const s = version.trim().replace(/^[vV]/, '');
  const key: (number | string)[] = [];
  for (const part of s.replaceAll('_', '-').split('.')) {
    let chunk = '';
    for (const ch of part) {
      if (ch >= '0' && ch <= '9') chunk += ch;
      else break;
    }
    key.push(chunk ? Number(chunk) : 0);
    const tail = chunk ? part.slice(chunk.length) : part;
    if (tail) key.push(tail);
  }
  return key;
}

function compareSemver(a: string, b: string): number {
  const ka = semverSortKey(a);
  const kb = semverSortKey(b);
  for (let i = 0; i < Math.max(ka.length, kb.length); i++) {
    const va = ka[i] ?? 0;
    const vb = kb[i] ?? 0;
    if (va === vb) continue;
    if (typeof va === 'number' && typeof vb === 'number') return va < vb ? -1 : 1;
    return String(va).localeCompare(String(vb));
  }
  return 0;
}

export function semverInAffectedSegment(version: string, segment: VersionRange): boolean {
  const hi = segment.to.trim();
  if (!hi) return false;
  let lo = (segment.from || '0').trim();
  if (INCOMPARABLE_VERSIONS.has(lo.toUpperCase())) lo = '0';
  const cmpLo = compareSemver(version, lo);
  const cmpHi = compareSemver(version, hi);
  if (segment.upper_inclusive) return cmpLo >= 0 && cmpHi <= 0;
  return cmpLo >= 0 && cmpHi < 0;
}

export function semverInAnyAffected(version: string, affectedRanges: VersionRange[]): boolean {
  if (!affectedRanges.length) return true;
  return affectedRanges.some(seg => semverInAffectedSegment(version, seg));
}

function pkgAtVersion(name: string, version: string): string {
  const ver = version.trim();
  return ver ? `${name}@${ver}` : name;
}

/** Ancestor paths from root to each installation of package@version. */
export function collectInstallationPaths(npmLsJson: Json, packageName: string, version: string): string[][] {
  const paths: string[][] = [];
  const seen = new Set<string>();
  const rootName = asString(npmLsJson.name).trim();
  const root = rootName ? pkgAtVersion(rootName, asString(npmLsJson.version)) : undefined;
  const initialAncestors = root ? [root] : [];

  const walk = (node: Json, ancestors: string[]): void => {
    for (const [depName, dep] of Object.entries(node.dependencies ?? {})) {
      if (!dep || typeof dep !== 'object') continue;
      const depNode = dep as Json;
      const label = pkgAtVersion(depName, asString(depNode.version));
      const path = [...ancestors, label];
      if (depName === packageName && asString(depNode.version).trim() === version) {
        const key = path.join('\0');
        if (!seen.has(key)) {
          seen.add(key);
          paths.push(path);
        }
      }
      walk(depNode, path);
    }
  };

  walk(npmLsJson, initialAncestors);
  return paths;
}

export function formatNpmLsSpine(path: string[]): string {
  if (!path.length) return '';
  if (path.length === 1) return `└── ${path[0]}`;
  const lines: string[] = [];
  for (let i = 0; i < path.length; i++) {
    const indent = '  '.repeat(i);
    if (i === 0) lines.push(`└─┬ ${path[i]}`);
    else if (i === path.length - 1) lines.push(`${indent}└── ${path[i]}`);
    else lines.push(`${indent}└─┬ ${path[i]}`);
  }
  return lines.join('\n');
}

export function formatInstallationPathNotes(paths: string[][]): string {
  return paths.map(path => formatNpmLsSpine(path)).filter(Boolean).join('\n\n');
}

export function vulnerablePatchVersions(
  versions: string[],
  cveIds: string[],
  cveDict: Record<string, CveDetails>,
): string[] {
  return sortVersions(
    versions.filter(ver =>
      cveIds.some(cveId =>
        semverInAnyAffected(ver, cveDict[normalizeCveId(cveId)]?.affected_ranges ?? []),
      ),
    ),
  );
}

export function vulnerabilityNoteForRow(
  row: ManifestRow,
  cveDict: Record<string, CveDetails>,
  npmLsJson: Json | undefined,
): string | undefined {
  const vulnerable = vulnerablePatchVersions(parsePatchVersions(row.patch_version), row.cve_ids, cveDict);
  if (!vulnerable.length) return undefined;

  const blocks: string[] = [];
  for (const ver of vulnerable) {
    blocks.push(`${row.package}@${ver} is still in CVE affected range; verify dev-only`);
    if (npmLsJson) {
      const spines = formatInstallationPathNotes(collectInstallationPaths(npmLsJson, row.package, ver));
      if (spines) blocks.push(spines);
    }
  }
  return AUTO_NOTE_PREFIX + blocks.join('\n');
}

export function stripAutoNotes(notes: string | undefined): string | undefined {
  if (!notes) return undefined;
  const idx = notes.indexOf(AUTO_NOTE_PREFIX);
  const manual = (idx >= 0 ? notes.slice(0, idx) : notes).trim();
  return manual || undefined;
}

export function mergeManifestNotes(manual: string | undefined, auto: string | undefined): string | undefined {
  const parts = [stripAutoNotes(manual), auto?.trim()].filter(Boolean);
  return parts.length ? parts.join('\n\n') : undefined;
}

function npmLsJsonForPackage(
  pluginsWorkspace: string,
  packageName: string,
  cache: Map<string, Json | undefined>,
): Json | undefined {
  if (cache.has(packageName)) return cache.get(packageName);
  let parsed: Json | undefined;
  try {
    const raw = exec(['npm', 'ls', packageName, '--json'], {
      cwd: pluginsWorkspace,
      quiet: true,
      ok: [0, 1],
    }).trim();
    parsed = raw ? (JSON.parse(raw) as Json) : undefined;
  } catch {
    console.error(`warning: npm ls failed for ${packageName}`);
    parsed = undefined;
  }
  cache.set(packageName, parsed);
  return parsed;
}

export function enrichManifestRowsWithVulnerabilityNotes(
  rows: ManifestRow[],
  cveDict: Record<string, CveDetails>,
  pluginsWorkspace: string,
): ManifestRow[] {
  const npmLsCache = new Map<string, Json | undefined>();
  return rows.map(row => {
    const auto = vulnerabilityNoteForRow(row, cveDict, npmLsJsonForPackage(pluginsWorkspace, row.package, npmLsCache));
    const notes = mergeManifestNotes(row.notes, auto);
    return notes
      ? { ...row, notes }
      : { cve_ids: row.cve_ids, package: row.package, patch_version: row.patch_version };
  });
}

async function ensureCveDict(
  cveIds: string[],
  existing: Record<string, CveDetails>,
): Promise<Record<string, CveDetails>> {
  const out = { ...existing };
  for (const cveId of cveIds) {
    const key = normalizeCveId(cveId);
    if (out[key]) continue;
    const res = await fetch(CVE_API + encodeURIComponent(key), {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(45_000),
    });
    if (!res.ok) throw new Error(`CVE lookup failed: HTTP ${res.status}`);
    const record = (await res.json()) as Json;
    if (record.dataType !== 'CVE_RECORD') throw new Error('unexpected CVE Record response');
    out[key] = parseCveDetails(record);
  }
  return out;
}

async function fetchCveDetails(
  tokens: Array<[string, string[]]>,
): Promise<Record<string, CveDetails>> {
  const out: Record<string, CveDetails> = {};
  for (const [cveId, overrides] of tokens) {
    const res = await fetch(CVE_API + encodeURIComponent(cveId), {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(45_000),
    });
    if (!res.ok) throw new Error(`CVE lookup failed: HTTP ${res.status}`);
    const record = (await res.json()) as Json;
    if (record.dataType !== 'CVE_RECORD') throw new Error('unexpected CVE Record response');
    out[cveId] = parseCveDetails(record, overrides.length ? overrides : undefined);
  }
  return out;
}

// --- shell / paths ---

function formatCmd(cmd: string[], cwd?: string): string {
  const cwdSuffix = cwd ? ` (cwd: ${cwd})` : '';
  return `> ${cmd.join(' ')}${cwdSuffix}`;
}

type SpawnStdio = 'inherit' | readonly ['pipe', 'pipe', 'pipe'] | readonly ['pipe', 'inherit', 'inherit'];

/** `input` requires piped stdin; inherit would silently drop it. */
function spawnStdio(quiet: boolean, hasInput: boolean): SpawnStdio {
  if (quiet) return ['pipe', 'pipe', 'pipe'];
  if (hasInput) return ['pipe', 'inherit', 'inherit'];
  return 'inherit';
}

function formatExecFailure(
  cmd: string[],
  opts: { cwd?: string },
  result: { error?: Error | null; status: number | null },
): string {
  return [
    `command failed: ${cmd.join(' ')}`,
    opts.cwd ? `cwd: ${opts.cwd}` : '',
    result.error ? asString(result.error.message) || 'spawn error' : '',
    result.status != null ? `exit ${result.status}` : '',
  ]
    .filter(Boolean)
    .join('\n');
}

function exec(
  cmd: string[],
  opts: { cwd?: string; input?: string; ok?: number[]; quiet?: boolean; dryRun?: boolean } = {},
): string {
  if (opts.dryRun) {
    console.log(formatCmd(cmd, opts.cwd));
    return '';
  }
  const quiet = opts.quiet ?? false;
  if (!quiet) console.log(formatCmd(cmd, opts.cwd));
  const result = spawnSync(cmd[0], cmd.slice(1), {
    cwd: opts.cwd,
    input: opts.input,
    encoding: 'utf-8',
    maxBuffer: SPAWN_MAX_BUFFER,
    stdio: spawnStdio(quiet, opts.input != null),
  });
  if (result.error || !(opts.ok ?? [0]).includes(result.status ?? -1)) {
    const stderr = asString(result.stderr).trim();
    const stdout = asString(result.stdout).trim();
    if (quiet && (stderr || stdout)) console.error(stderr || stdout);
    const summary = formatExecFailure(cmd, opts, result);
    console.error(summary);
    throw new Error(summary);
  }
  return quiet ? asString(result.stdout) : '';
}

function validateGitRef(ref: string): string {
  const trimmed = ref.trim();
  if (trimmed.startsWith('-')) throw new Error('invalid git ref');
  if (/^[0-9a-f]{7,40}$/i.test(trimmed)) return trimmed;
  if (/^[A-Za-z0-9._/-]+$/.test(trimmed) && !trimmed.includes('..')) return trimmed;
  throw new Error('invalid git ref');
}

/** Canonical trusted root with trailing separator (path-traversal mitigation). */
export function canonicalBaseDir(raw: string, label: string): string {
  const trimmed = raw.trim();
  if (!trimmed) throw new Error(`${label} is empty`);
  if (!isAbsolute(trimmed)) throw new Error(`${label} must be an absolute path`);
  const resolved = resolve(trimmed);
  const canonical = existsSync(resolved) ? realpathSync(resolved) : resolved;
  return canonical.endsWith(sep) ? canonical : `${canonical}${sep}`;
}

/** Resolve a path under baseDir; reject if it escapes the base. */
export function pathUnderBase(baseDir: string, ...parts: string[]): string {
  const filePath = join(baseDir, ...parts);
  const canonical = existsSync(filePath) ? realpathSync(filePath) : resolve(filePath);
  if (!canonical.startsWith(baseDir)) throw new Error('Access denied');
  return canonical;
}

type WorkspacePaths = {
  overlayWorkspace: string;
  pluginsRepo: string;
  pluginsWorkspace: string;
  patchPath: string;
  manifestPath: string;
  sourceJsonPath: string;
  localLockPath: string;
  name: string;
};

function resolveWorkspacePaths(overlay: string, pluginsRepo: string): WorkspacePaths {
  const overlayBase = canonicalBaseDir(overlay, 'overlay-workspace');
  const pluginsBase = canonicalBaseDir(pluginsRepo, 'plugins-repo');
  const name = basename(overlayBase.slice(0, -1));
  if (!name || name === '.' || name === '..') throw new Error('invalid overlay-workspace path');

  return {
    overlayWorkspace: overlayBase.slice(0, -1),
    pluginsRepo: pluginsBase.slice(0, -1),
    pluginsWorkspace: pathUnderBase(pluginsBase, 'workspaces', name),
    patchPath: pathUnderBase(overlayBase, 'patches', PATCH_FILE),
    manifestPath: pathUnderBase(overlayBase, 'patches', MANIFEST),
    sourceJsonPath: pathUnderBase(overlayBase, 'source.json'),
    localLockPath: pathUnderBase(pluginsBase, 'workspaces', name, LOCKFILE),
    name,
  };
}

/** `owner/repo` slug from source.json `repo` (HTTPS, SSH, or github.com tree URLs). */
export function canonicalRepoFromUrl(repoUrl: string): string {
  const trimmed = repoUrl.trim();
  if (!trimmed) throw new Error('source.json repo URL is empty');
  const match = /github\.com[/:]([^/]+\/[^/?#]+)/i.exec(trimmed);
  const slug = match?.[1]?.replace(/\.git$/i, '');
  if (!slug) throw new Error(`unsupported source.json repo URL: ${repoUrl}`);
  return slug;
}

function readSource(sourceJsonPath: string) {
  if (!existsSync(sourceJsonPath)) throw new Error('missing source.json in overlay workspace');
  const data = JSON.parse(readFileSync(sourceJsonPath, 'utf-8')) as Json;
  return {
    repoRef: validateGitRef(asString(data['repo-ref'])),
    sourceRepo: canonicalRepoFromUrl(asString(data.repo).trim()),
  };
}

function readManifest(manifestPath: string): ManifestRow[] {
  if (!existsSync(manifestPath)) return [];
  const data = parseYaml(readFileSync(manifestPath, 'utf-8')) as Json;
  const rows = data.backports;
  if (rows == null) return [];
  if (!Array.isArray(rows)) throw new Error('cve-backports.yaml: backports must be a list');
  return rows as ManifestRow[];
}

export function releaseBranch(release: string): string {
  const trimmed = release.trim();
  if (!trimmed) throw new Error('release is empty');
  return trimmed.startsWith('release-') ? trimmed : `release-${trimmed}`;
}

export function validateReleaseBranch(release: string): string {
  const branch = releaseBranch(release);
  const suffix = branch.slice('release-'.length);
  if (!/^\d+(\.\d+)*(?:-[A-Za-z0-9._-]+)?$/.test(suffix)) {
    throw new Error('invalid release version');
  }
  return branch;
}

function gitRepoRoot(startPath: string): string {
  const root = exec(['git', 'rev-parse', '--show-toplevel'], { cwd: startPath, quiet: true }).trim();
  if (!root) throw new Error('not a git repository');
  return root;
}

export function resolveGitRemote(remotesListing: string, originUrl: string, canonicalRepo: string): string {
  const upstreamUrl = /^upstream\t([^\s]+)/m.exec(remotesListing)?.[1] ?? '';
  if (upstreamUrl.includes(canonicalRepo)) return 'upstream';
  if (originUrl.includes(canonicalRepo)) return 'origin';
  throw new Error('git repo has no upstream remote (fork setup)');
}

function gitRemote(root: string, canonicalRepo: string): string {
  const listing = exec(['git', 'remote', '-v'], { cwd: root, quiet: true });
  const originUrl = exec(['git', 'remote', 'get-url', 'origin'], { cwd: root, quiet: true }).trim();
  return resolveGitRemote(listing, originUrl, canonicalRepo);
}

function syncPluginsRepo(
  pluginsRepo: string,
  repoRef: string,
  sourceRepo: string,
  dryRun?: boolean,
  verbose?: boolean,
): void {
  const remote = gitRemote(pluginsRepo, sourceRepo);
  console.log(`Syncing source repo from ${remote}`);
  const quiet = !verbose;
  exec(['git', 'fetch', remote], { cwd: pluginsRepo, dryRun, quiet });
  exec(['git', 'fetch', remote, '--', repoRef], { cwd: pluginsRepo, dryRun, quiet });
  exec(['git', '-c', 'advice.detachedHead=false', 'checkout', '-q', repoRef], {
    cwd: pluginsRepo,
    dryRun,
    quiet,
  });
}

function ensureOverlayRelease(
  overlayWorkspace: string,
  release: string,
  opts: { dryRun?: boolean; force?: boolean },
): void {
  const branch = validateReleaseBranch(release);
  const root = gitRepoRoot(overlayWorkspace);
  const remote = gitRemote(root, OVERLAY_UPSTREAM_REPO);
  const remoteRef = `${remote}/${branch}`;

  if (!opts.force && !opts.dryRun) {
    const dirty = exec(['git', 'status', '--porcelain'], { cwd: root, quiet: true });
    if (dirty) throw new Error('overlay repo has uncommitted changes; commit/stash or pass --force');
  }

  console.log(`Syncing overlay repo to ${branch} from ${remote}`);
  exec(['git', 'fetch', remote, branch], { cwd: root, dryRun: opts.dryRun });

  const current = opts.dryRun
    ? ''
    : exec(['git', 'branch', '--show-current'], { cwd: root, quiet: true }).trim();
  if (current !== branch) {
    exec(['git', 'checkout', '-B', branch, remoteRef], { cwd: root, dryRun: opts.dryRun });
  } else {
    exec(['git', 'merge', '--ff-only', remoteRef], { cwd: root, dryRun: opts.dryRun });
  }
}

function logContext(release: string, workspaceName: string) {
  console.log(`RHDH release: ${release} (${releaseBranch(release)})`);
  console.log(`workspace:     ${workspaceName}`);
}

function escPkg(pkg: string): string {
  return pkg.replace(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);
}

function sortVersions(versions: string[]): string[] {
  return [...new Set(versions.filter(Boolean))].sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true }),
  );
}

export function formatPatchVersions(versions: string[]): string {
  return sortVersions(versions).join(', ');
}

export function parsePatchVersions(value: string): string[] {
  return sortVersions(value.split(',').map(v => v.trim()));
}

/** Distinct versions of pkg in a Yarn Berry lockfile. */
export function versionsInLock(text: string, pkg: string): string[] {
  return sortVersions(
    [...text.matchAll(new RegExp(`resolution: "${escPkg(pkg)}@npm:([^"]+)"`, 'gm'))].map(m => m[1]),
  );
}

/** First package name from CVE details that appears in yarn.lock. */
export function resolvePackageInLock(
  names: string[],
  lockText: string,
): { package: string; versions: string[] } | undefined {
  for (const pkg of names) {
    if (!pkg) continue;
    const versions = versionsInLock(lockText, pkg);
    if (versions.length) return { package: pkg, versions };
  }
  return undefined;
}

export function requireLockfileChange(baseline: string, patched: string): void {
  if (baseline === patched) {
    throw new Error(
      'yarn.lock unchanged from repo-ref baseline; bump vulnerable packages before generate',
    );
  }
}

function writeLockPatch(baseline: string, patched: string, patchPath: string, dryRun: boolean): void {
  requireLockfileChange(baseline, patched);
  const tmp = mkdtempSync(join(tmpdir(), 'yarnlock-backport-'));
  try {
    const a = join(tmp, 'a.lock');
    const b = join(tmp, 'b.lock');
    writeFileSync(a, baseline);
    writeFileSync(b, patched);
    const diff = spawnSync(BIN_DIFF, ['-u', '--label', LOCKFILE, '--label', LOCKFILE, a, b], {
      encoding: 'utf-8',
      maxBuffer: SPAWN_MAX_BUFFER,
    });
    if (diff.error || (diff.status !== 0 && diff.status !== 1)) throw new Error('diff failed');
    let body = diff.stdout ?? '';
    if (!body.trim()) {
      console.log('diff produced no output; no patch written');
      return;
    }
    if (!body.endsWith('\n')) body += '\n';

    const verify = join(tmp, 'verify');
    mkdirSync(verify);
    writeFileSync(join(verify, LOCKFILE), baseline);
    const check = spawnSync(BIN_PATCH, ['-p0', '--dry-run', '-l', '--no-backup-if-mismatch', '-f'], {
      cwd: verify,
      input: body,
      encoding: 'utf-8',
      maxBuffer: SPAWN_MAX_BUFFER,
    });
    if (check.status !== 0) throw new Error('generated patch failed dry-run verification');

    if (dryRun) {
      console.log(`[dry-run] would write ${PATCH_FILE} (${body.length} bytes)`);
      return;
    }
    mkdirSync(dirname(patchPath), { recursive: true });
    writeFileSync(patchPath, body);
    console.log(`Wrote ${PATCH_FILE}`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function notesByCveId(manifestPath: string): Map<string, string> {
  const notes = new Map<string, string>();
  for (const row of readManifest(manifestPath)) {
    const text = stripAutoNotes(asString(row.notes).trim());
    if (!text) continue;
    for (const id of row.cve_ids ?? []) {
      const cveId = asString(id).trim();
      if (cveId) notes.set(normalizeCveId(cveId), text);
    }
  }
  return notes;
}

function manifestEntries(manifestPath: string): ManifestEntry[] {
  const entries: ManifestEntry[] = [];
  for (const row of readManifest(manifestPath)) {
    const pkg = asString(row.package).trim();
    const vers = parsePatchVersions(asString(row.patch_version));
    const notes = asString(row.notes).trim() || undefined;
    if (!pkg || !vers.length) continue;
    for (const id of row.cve_ids ?? []) {
      const cveId = asString(id).trim();
      if (cveId) {
        entries.push({
          cveId: normalizeCveId(cveId),
          package: pkg,
          patch_versions: vers,
          notes,
        });
      }
    }
  }
  return entries;
}

export function buildManifestRows(entries: ManifestEntry[]): ManifestRow[] {
  const groups = new Map<string, ManifestRow>();
  for (const { cveId, package: pkg, patch_versions, notes } of [...entries].sort(
    (a, b) =>
      a.cveId.localeCompare(b.cveId) ||
      a.package.localeCompare(b.package) ||
      formatPatchVersions(a.patch_versions).localeCompare(formatPatchVersions(b.patch_versions)),
  )) {
    const patch_version = formatPatchVersions(patch_versions);
    const key = `${pkg}\0${patch_version}`;
    const row = groups.get(key) ?? { cve_ids: [], package: pkg, patch_version };
    if (!row.cve_ids.includes(cveId)) row.cve_ids.push(cveId);
    if (notes && !row.notes) row.notes = notes;
    groups.set(key, row);
  }
  return [...groups.values()]
    .sort((a, b) => a.package.localeCompare(b.package) || a.patch_version.localeCompare(b.patch_version))
    .map(r => {
      const row: ManifestRow = {
        cve_ids: [...r.cve_ids].sort((a, b) => a.localeCompare(b)),
        package: r.package,
        patch_version: r.patch_version,
      };
      if (r.notes) row.notes = r.notes;
      return row;
    });
}

export function formatManifestDocument(repoRef: string, rows: ManifestRow[]): string {
  return (
    MANIFEST_HEADER +
    stringifyYaml({ patch_file: PATCH_FILE, repo_ref: repoRef, backports: rows }, { lineWidth: 0 })
  );
}

async function updateManifest(opts: {
  manifestPath: string;
  repoRef: string;
  cveIds: string[];
  cveDict: Record<string, CveDetails>;
  pluginsWorkspace: string;
  lockText: string;
  dryRun: boolean;
}): Promise<{ touched: Set<string>; skipped: string[]; rows: ManifestRow[] }> {
  const updateIds = new Set(opts.cveIds.map(id => normalizeCveId(id)));
  const preservedNotes = notesByCveId(opts.manifestPath);
  const entries = manifestEntries(opts.manifestPath).filter(e => !updateIds.has(e.cveId));

  const touched = new Set<string>();
  const skipped: string[] = [];
  for (const cveId of opts.cveIds) {
    const key = normalizeCveId(cveId);
    const cve = opts.cveDict[key];
    if (!cve?.names?.length) throw new Error(`no npm package resolved for ${key}`);
    const resolved = resolvePackageInLock(cve.names, opts.lockText);
    if (!resolved) {
      skipped.push(`${key} (${cve.names.join(', ')}): not in yarn.lock`);
      continue;
    }
    entries.push({
      cveId: key,
      package: resolved.package,
      patch_versions: resolved.versions,
      notes: preservedNotes.get(key),
    });
    touched.add(key);
  }

  const fullCveDict = await ensureCveDict(
    [...new Set(entries.map(e => e.cveId))],
    opts.cveDict,
  );
  const rows = enrichManifestRowsWithVulnerabilityNotes(
    buildManifestRows(entries),
    fullCveDict,
    opts.pluginsWorkspace,
  );
  if (!opts.dryRun) {
    mkdirSync(dirname(opts.manifestPath), { recursive: true });
    writeFileSync(opts.manifestPath, formatManifestDocument(opts.repoRef, rows));
    console.log(`Wrote ${MANIFEST}`);
  }

  return {
    touched,
    skipped,
    rows: rows.filter(r => r.cve_ids.some(id => touched.has(id))),
  };
}

function printReroll(workspaceName: string, bumps: string[]) {
  console.error(`\nPatch ${PATCH_FILE} failed — yarn.lock at repo-ref no longer matches the patch baseline.`);
  console.error('Re-roll: update dependencies', bumps.length ? [...new Set(bumps)].join(' ') : '(Instructions TBD)');
  console.error(`  in plugins workspace: ${workspaceName}`);
  console.error('  yarnlock-backport generate --release … --cve …');
}

function manifestBumpSpecs(manifestPath: string): string[] {
  const bumps: string[] = [];
  for (const row of readManifest(manifestPath)) {
    const pkg = asString(row.package).trim();
    if (!pkg) continue;
    for (const ver of parsePatchVersions(asString(row.patch_version))) {
      if (ver) bumps.push(`${pkg}@${ver}`);
    }
  }
  return bumps;
}

function assertPluginsRepoClean(pluginsRepo: string, opts: { force?: boolean; dryRun?: boolean; verbose?: boolean }): void {
  if (opts.force || opts.dryRun) return;
  // Always capture stdout — inherit would make dirty checks silently pass.
  const dirty = exec(['git', 'status', '--porcelain'], { cwd: pluginsRepo, quiet: true });
  if (dirty) throw new Error('plugins repo has uncommitted changes; commit/stash or pass --force');
}

function patchStripArgs(patchData: string): string[] {
  return patchData.includes('diff --git') || patchData.includes('--- a/') ? ['-p1'] : ['-p0'];
}

/** Apply existing 0-cve-yarn-lock.patch (or skip / no-op). */
function applyExistingCvePatch(ctx: WorkspacePaths, opts: { skipPatch?: boolean; dryRun?: boolean }): void {
  if (opts.skipPatch) {
    console.log('Skipping patch (--skip-patch). Next: yarnlock-backport generate …');
    return;
  }
  if (!existsSync(ctx.patchPath)) {
    console.log(`No ${PATCH_FILE}; starting from repo-ref baseline`);
    return;
  }

  const patchData = readFileSync(ctx.patchPath, 'utf-8');
  const strip = patchStripArgs(patchData);
  console.log(`Step 1b: applying ${PATCH_FILE}`);

  if (opts.dryRun) {
    exec([BIN_PATCH, ...strip, '--dry-run', '-l', '--no-backup-if-mismatch', '-f'], {
      cwd: ctx.pluginsWorkspace,
      input: patchData,
      quiet: true,
    });
    return;
  }

  const result = spawnSync(BIN_PATCH, [...strip, '-l', '--no-backup-if-mismatch', '-f'], {
    cwd: ctx.pluginsWorkspace,
    input: patchData,
    encoding: 'utf-8',
    maxBuffer: SPAWN_MAX_BUFFER,
  });
  if (result.status === 0) {
    console.log('Patch applied. Next: yarnlock-backport generate …');
    return;
  }
  printReroll(ctx.name, manifestBumpSpecs(ctx.manifestPath));
  throw new Error(`failed to apply ${PATCH_FILE}`);
}

// --- commands ---

export async function prepareWorkspace(opts: {
  release: string;
  overlayWorkspace: string;
  pluginsRepo: string;
  skipPatch?: boolean;
  force?: boolean;
  dryRun?: boolean;
  verbose?: boolean;
}): Promise<void> {
  const ctx = resolveWorkspacePaths(opts.overlayWorkspace, opts.pluginsRepo);
  ensureOverlayRelease(ctx.overlayWorkspace, opts.release, { dryRun: opts.dryRun, force: opts.force });
  const { repoRef, sourceRepo } = readSource(ctx.sourceJsonPath);
  logContext(opts.release, ctx.name);

  assertPluginsRepoClean(ctx.pluginsRepo, opts);
  syncPluginsRepo(ctx.pluginsRepo, repoRef, sourceRepo, opts.dryRun, opts.verbose);
  if (!opts.dryRun && !existsSync(ctx.pluginsWorkspace)) throw new Error('missing plugins workspace');

  console.log('Step 1a: yarn install');
  exec(['yarn', 'install'], { cwd: ctx.pluginsWorkspace, dryRun: opts.dryRun });
  applyExistingCvePatch(ctx, opts);
}

export async function generateBackport(opts: {
  release: string;
  overlayWorkspace: string;
  pluginsRepo: string;
  cve: string;
  dryRun?: boolean;
  verbose?: boolean;
}): Promise<void> {
  const ctx = resolveWorkspacePaths(opts.overlayWorkspace, opts.pluginsRepo);
  ensureOverlayRelease(ctx.overlayWorkspace, opts.release, { dryRun: opts.dryRun });
  const { repoRef, sourceRepo } = readSource(ctx.sourceJsonPath);
  logContext(opts.release, ctx.name);

  if (!existsSync(ctx.localLockPath)) throw new Error(`missing local ${LOCKFILE}`);
  if (!opts.dryRun && !existsSync(ctx.pluginsWorkspace)) throw new Error('missing plugins workspace');

  console.log('yarn install');
  exec(['yarn', 'install'], { cwd: ctx.pluginsWorkspace, dryRun: opts.dryRun });

  const remote = gitRemote(ctx.pluginsRepo, sourceRepo);
  exec(['git', 'fetch', remote, '--', repoRef], { cwd: ctx.pluginsRepo, dryRun: opts.dryRun });
  const baseline = exec(['git', 'show', `${repoRef}:workspaces/${ctx.name}/${LOCKFILE}`], {
    cwd: ctx.pluginsRepo,
    quiet: true,
  });
  const patched = readFileSync(ctx.localLockPath, 'utf-8');
  if (!opts.dryRun) requireLockfileChange(baseline, patched);

  const tokens = parseCveArg(opts.cve);
  const cveDict = await fetchCveDetails(tokens);
  const cveIds = tokens.map(([id]) => id);
  const manifestOpts = {
    manifestPath: ctx.manifestPath,
    repoRef,
    cveIds,
    cveDict,
    pluginsWorkspace: ctx.pluginsWorkspace,
    lockText: patched,
  };

  const preview = await updateManifest({ ...manifestOpts, dryRun: true });
  if (!preview.touched.size && preview.skipped.length) {
    throw new Error('no CVE packages from --cve are present in this workspace yarn.lock');
  }

  writeLockPatch(baseline, patched, ctx.patchPath, opts.dryRun ?? false);
  if (!opts.dryRun) await updateManifest({ ...manifestOpts, dryRun: false });

  const prefix = opts.dryRun ? '[dry-run] ' : '';
  if (preview.rows.length) console.log(`\n${prefix}Recorded ${preview.rows.length} manifest row(s)`);
  for (const skip of preview.skipped) console.error(`warning: skipping ${skip}`);
}
