import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const OVERLAY_UPSTREAM_REPO = 'redhat-developer/rhdh-plugin-export-overlays';
const PLUGINS_UPSTREAM_REPO = 'redhat-developer/rhdh-plugins';
/** orchestrator yarn.lock is ~1.5 MiB; Node spawnSync default maxBuffer is 1 MiB */
const SPAWN_MAX_BUFFER = 64 * 1024 * 1024;
const PATCH_FILE = '0-cve-yarn-lock.patch';
const MANIFEST = 'cve-backports.yaml';
const LOCKFILE = 'yarn.lock';
const CVE_API = 'https://cveawg.mitre.org/api/cve/';
const CVE_ID_RE = /^CVE-\d{4}-\d+$/i;
const MANIFEST_HEADER = `# CVE backports applied via workspace patches (not repo-ref bumps).
# Auto-generated by scripts/yarnlock-backport.
# Optional: add notes on any backport row (preserved when you re-run generate).

`;

type Json = Record<string, unknown>;
type VersionRange = { from: string; to: string; upper_inclusive: boolean };
type ManifestRow = { cve_ids: string[]; package: string; patch_version: string; notes?: string };
type CveDetails = { name: string; names: string[]; patch_versions: string[]; affected_ranges: VersionRange[] };

const INCOMPARABLE_VERSIONS = new Set(['0', '*', 'N/A', 'NA']);
const AUTO_NOTE_PREFIX = '[auto] ';

// --- CVE (MITRE) ---

export function normalizeCveId(cveId: string): string {
  const id = cveId.trim().toUpperCase().replace(/ /g, '');
  if (!CVE_ID_RE.test(id)) throw new Error('not a CVE id');
  return id;
}

export function parseCveCliToken(raw: string): [string, string[]] {
  const text = raw.trim().replace(/ /g, '');
  if (!text) throw new Error('empty CVE token');
  const slash = text.indexOf('/');
  const cveId = normalizeCveId(slash >= 0 ? text.slice(0, slash) : text);
  const overrides = (slash >= 0 ? text.slice(slash + 1) : '').split(',').map(s => s.trim()).filter(Boolean);
  return [cveId, overrides];
}

export function parseCveArg(raw: string): string[] {
  const tokens = raw.split(',').map(t => t.trim()).filter(Boolean);
  if (!tokens.length) throw new Error('CVE list is empty');
  const seen = new Set<string>();
  return tokens.map(token => {
    const [cveId] = parseCveCliToken(token);
    if (seen.has(cveId)) throw new Error('duplicate CVE in --cve list');
    seen.add(cveId);
    return token;
  });
}

function versionEntryToRanges(v: Json): { fixes: string[]; ranges: VersionRange[] } {
  const fixes: string[] = [];
  const ranges: VersionRange[] = [];
  if (String(v.status ?? '').toLowerCase() !== 'affected') return { fixes, ranges };

  const lowRaw = String(v.version ?? '').trim();
  const loDefault = lowRaw && !INCOMPARABLE_VERSIONS.has(lowRaw.toUpperCase()) ? lowRaw : '0';

  if (v.lessThan != null && String(v.lessThan).trim()) {
    const hi = String(v.lessThan).trim();
    fixes.push(hi);
    ranges.push({ from: loDefault, to: hi, upper_inclusive: false });
  }
  if (v.lessThanOrEqual != null && String(v.lessThanOrEqual).trim()) {
    const hi = String(v.lessThanOrEqual).trim();
    fixes.push(hi);
    ranges.push({ from: loDefault, to: hi, upper_inclusive: true });
  }

  const compound = lowRaw.match(/>=\s*([\w.-]+)\s*,\s*<\s*([\w.-]+)/);
  if (compound) {
    ranges.push({ from: compound[1], to: compound[2], upper_inclusive: false });
    fixes.push(compound[2]);
    return { fixes: [...new Set(fixes.filter(Boolean))], ranges };
  }

  if (!ranges.length && lowRaw) {
    const lte = lowRaw.match(/^\s*<=\s*([\w.-]+)\s*$/);
    if (lte) {
      const hi = lte[1].trim();
      ranges.push({ from: '0', to: hi, upper_inclusive: true });
      fixes.push(hi);
      return { fixes: [...new Set(fixes.filter(Boolean))], ranges };
    }
    const lt = lowRaw.match(/^\s*<\s*([\w.-]+)\s*$/);
    if (lt) {
      const hi = lt[1].trim();
      ranges.push({ from: '0', to: hi, upper_inclusive: false });
      fixes.push(hi);
      return { fixes: [...new Set(fixes.filter(Boolean))], ranges };
    }
    const gte = lowRaw.match(/^\s*>=\s*([\w.-]+)\s*$/);
    if (gte) {
      ranges.push({ from: gte[1].trim(), to: '99999.0.0', upper_inclusive: true });
      return { fixes, ranges };
    }
  }

  return { fixes: [...new Set(fixes.filter(Boolean))], ranges };
}

function parseAffectedRanges(ranges: VersionRange[]): VersionRange[] {
  return ranges.filter(r => r.to);
}

function collectPackageCveData(affected: Json[]): { fixes: string[]; ranges: VersionRange[] } {
  const fixes: string[] = [];
  const ranges: VersionRange[] = [];
  for (const entry of affected) {
    for (const versionEntry of (entry.versions as Json[]) ?? []) {
      const parsed = versionEntryToRanges(versionEntry);
      fixes.push(...parsed.fixes);
      ranges.push(...parsed.ranges);
    }
  }
  return { fixes, ranges };
}

function fixesFromVersion(v: Json): string[] {
  return versionEntryToRanges(v).fixes;
}

export function parseCveDetails(record: Json, overrideNames?: string[]): CveDetails {
  const empty = { name: '', names: [], patch_versions: [], affected_ranges: [] };
  const meta = (record.cveMetadata as Json) ?? {};
  if (String(meta.state ?? '').toUpperCase() === 'REJECTED') return empty;

  const affected = (((record.containers as Json)?.cna as Json)?.affected as Json[]) ?? [];

  if (overrideNames?.length) {
    const { fixes, ranges } = collectPackageCveData(affected);
    return {
      name: overrideNames[0],
      names: [...overrideNames],
      patch_versions: [...new Set(fixes)],
      affected_ranges: parseAffectedRanges(ranges),
    };
  }

  const byPackage = new Map<string, { fixes: string[]; ranges: VersionRange[] }>();
  for (const entry of affected) {
    for (const key of ['packageName', 'product', 'vendor']) {
      const name = String(entry[key] ?? '').trim();
      if (!name) continue;
      const parsed = collectPackageCveData([entry]);
      const slot = byPackage.get(name) ?? { fixes: [], ranges: [] };
      slot.fixes.push(...parsed.fixes);
      slot.ranges.push(...parsed.ranges);
      byPackage.set(name, slot);
      break;
    }
  }
  if (!byPackage.size) return empty;

  const [name, slot] = [...byPackage.entries()].sort(
    (a, b) => b[1].fixes.length + b[1].ranges.length - (a[1].fixes.length + a[1].ranges.length) || a[0].localeCompare(b[0]),
  )[0];
  return {
    name,
    names: [name],
    patch_versions: [...new Set(slot.fixes)],
    affected_ranges: parseAffectedRanges(slot.ranges),
  };
}

/** Semver-ish sort key (from rhdh-security/triage/branch-check.py). */
export function semverSortKey(version: string): (number | string)[] {
  const s = version.trim().replace(/^[vV]/, '');
  const key: (number | string)[] = [];
  for (const part of s.replace(/_/g, '-').split('.')) {
    let chunk = '';
    for (const ch of part) {
      if (ch >= '0' && ch <= '9') chunk += ch;
      else break;
    }
    key.push(chunk ? Number(chunk) : 0);
    const tail = chunk ? part.slice(chunk.length) : part;
    if (tail) key.push(tail);
  }
  return key;
}

function compareSemver(a: string, b: string): number {
  const ka = semverSortKey(a);
  const kb = semverSortKey(b);
  for (let i = 0; i < Math.max(ka.length, kb.length); i++) {
    const va = ka[i] ?? 0;
    const vb = kb[i] ?? 0;
    if (va === vb) continue;
    if (typeof va === 'number' && typeof vb === 'number') return va < vb ? -1 : 1;
    return String(va).localeCompare(String(vb));
  }
  return 0;
}

export function semverInAffectedSegment(version: string, segment: VersionRange): boolean {
  const hi = segment.to.trim();
  if (!hi) return false;
  let lo = (segment.from || '0').trim();
  if (INCOMPARABLE_VERSIONS.has(lo.toUpperCase())) lo = '0';
  const cmpLo = compareSemver(version, lo);
  const cmpHi = compareSemver(version, hi);
  if (segment.upper_inclusive) return cmpLo >= 0 && cmpHi <= 0;
  return cmpLo >= 0 && cmpHi < 0;
}

export function semverInAnyAffected(version: string, affectedRanges: VersionRange[]): boolean {
  if (!affectedRanges.length) return true;
  return affectedRanges.some(seg => semverInAffectedSegment(version, seg));
}

function depLabel(depName: string, depNode: Json): string {
  const version = String(depNode.version ?? '').trim();
  return version ? `${depName}@${version}` : depName;
}

function rootLabel(npmLsJson: Json): string | undefined {
  const name = String(npmLsJson.name ?? '').trim();
  const version = String(npmLsJson.version ?? '').trim();
  if (name && version) return `${name}@${version}`;
  return name || undefined;
}

/** Return ancestor paths from root to each installation of package@version. */
export function collectInstallationPaths(npmLsJson: Json, packageName: string, version: string): string[][] {
  const paths: string[][] = [];
  const seen = new Set<string>();
  const root = rootLabel(npmLsJson);
  const initialAncestors = root ? [root] : [];

  const walk = (node: Json, ancestors: string[]): void => {
    for (const [depName, dep] of Object.entries(node.dependencies ?? {})) {
      if (!dep || typeof dep !== 'object') continue;
      const depNode = dep as Json;
      const label = depLabel(depName, depNode);
      const path = [...ancestors, label];
      const depVersion = String(depNode.version ?? '').trim();
      if (depName === packageName && depVersion === version) {
        const key = path.join('\0');
        if (!seen.has(key)) {
          seen.add(key);
          paths.push(path);
        }
      }
      walk(depNode, path);
    }
  };

  walk(npmLsJson, initialAncestors);
  return paths;
}

export function formatNpmLsSpine(path: string[]): string {
  if (!path.length) return '';
  if (path.length === 1) return `└── ${path[0]}`;
  const lines: string[] = [];
  for (let i = 0; i < path.length; i++) {
    const indent = '  '.repeat(i);
    if (i === 0) lines.push(`└─┬ ${path[i]}`);
    else if (i === path.length - 1) lines.push(`${indent}└── ${path[i]}`);
    else lines.push(`${indent}└─┬ ${path[i]}`);
  }
  return lines.join('\n');
}

export function vulnerablePatchVersions(
  versions: string[],
  cveIds: string[],
  cveDict: Record<string, CveDetails>,
): string[] {
  return sortVersions(
    versions.filter(ver =>
      cveIds.some(cveId => semverInAnyAffected(ver, cveDict[normalizeCveId(cveId)]?.affected_ranges ?? [])),
    ),
  );
}

export function vulnerabilityNoteForRow(
  row: ManifestRow,
  cveDict: Record<string, CveDetails>,
  npmLsJson: Json | undefined,
): string | undefined {
  const versions = parsePatchVersions(row.patch_version);
  const vulnerable = vulnerablePatchVersions(versions, row.cve_ids, cveDict);
  if (!vulnerable.length) return undefined;

  const blocks: string[] = [];
  for (const ver of vulnerable) {
    blocks.push(`${row.package}@${ver} is still in CVE affected range; verify dev-only`);
    if (npmLsJson) {
      const paths = collectInstallationPaths(npmLsJson, row.package, ver);
      if (paths.length) blocks.push(formatNpmLsSpine(paths[0]));
    }
  }
  return AUTO_NOTE_PREFIX + blocks.join('\n');
}

export function stripAutoNotes(notes: string | undefined): string | undefined {
  if (!notes) return undefined;
  const idx = notes.indexOf(AUTO_NOTE_PREFIX);
  const manual = (idx >= 0 ? notes.slice(0, idx) : notes).trim();
  return manual || undefined;
}

export function mergeManifestNotes(manual: string | undefined, auto: string | undefined): string | undefined {
  const parts = [stripAutoNotes(manual), auto?.trim()].filter(Boolean);
  return parts.length ? parts.join('\n\n') : undefined;
}

function npmLsJsonForPackage(pluginsWorkspace: string, packageName: string, cache: Map<string, Json | undefined>): Json | undefined {
  if (cache.has(packageName)) return cache.get(packageName);
  let parsed: Json | undefined;
  try {
    const raw = exec(['npm', 'ls', packageName, '--json'], { cwd: pluginsWorkspace, quiet: true, ok: [0, 1] }).trim();
    parsed = raw ? (JSON.parse(raw) as Json) : undefined;
  } catch {
    console.error(`warning: npm ls failed for ${packageName}`);
    parsed = undefined;
  }
  cache.set(packageName, parsed);
  return parsed;
}

export function enrichManifestRowsWithVulnerabilityNotes(
  rows: ManifestRow[],
  cveDict: Record<string, CveDetails>,
  pluginsWorkspace: string,
): ManifestRow[] {
  const npmLsCache = new Map<string, Json | undefined>();
  return rows.map(row => {
    const npmLs = npmLsJsonForPackage(pluginsWorkspace, row.package, npmLsCache);
    const auto = vulnerabilityNoteForRow(row, cveDict, npmLs);
    const notes = mergeManifestNotes(row.notes, auto);
    return notes ? { ...row, notes } : { cve_ids: row.cve_ids, package: row.package, patch_version: row.patch_version };
  });
}

async function ensureCveDict(cveIds: string[], existing: Record<string, CveDetails>): Promise<Record<string, CveDetails>> {
  const out = { ...existing };
  for (const cveId of cveIds) {
    const key = normalizeCveId(cveId);
    if (out[key]) continue;
    const url = CVE_API + encodeURIComponent(key);
    const res = await fetch(url, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(45_000) });
    if (!res.ok) throw new Error(`CVE lookup failed: HTTP ${res.status}`);
    const record = (await res.json()) as Json;
    if (record.dataType !== 'CVE_RECORD') throw new Error('unexpected CVE Record response');
    out[key] = parseCveDetails(record);
  }
  return out;
}

async function fetchAllCveDetails(tokens: string[]): Promise<Record<string, CveDetails>> {
  const out: Record<string, CveDetails> = {};
  for (const token of tokens) {
    const [cveId, overrides] = parseCveCliToken(token);
    const url = CVE_API + encodeURIComponent(cveId);
    const res = await fetch(url, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(45_000) });
    if (!res.ok) throw new Error(`CVE lookup failed: HTTP ${res.status}`);
    const record = (await res.json()) as Json;
    if (record.dataType !== 'CVE_RECORD') throw new Error('unexpected CVE Record response');
    out[cveId] = parseCveDetails(record, overrides.length ? overrides : undefined);
  }
  return out;
}

// --- shell / paths ---

function spawnText(cmd: string, args: string[], opts: { cwd?: string; input?: string } = {}) {
  return spawnSync(cmd, args, {
    cwd: opts.cwd,
    input: opts.input,
    encoding: 'utf-8',
    maxBuffer: SPAWN_MAX_BUFFER,
  });
}

function exec(cmd: string[], opts: { cwd?: string; input?: string; ok?: number[]; quiet?: boolean; dryRun?: boolean } = {}): string {
  if (opts.dryRun) {
    console.log(`> ${cmd[0]}`);
    return '';
  }
  if (!opts.quiet) console.log(`> ${cmd[0]}`);
  const result = spawnSync(cmd[0], cmd.slice(1), {
    cwd: opts.cwd,
    input: opts.input,
    encoding: 'utf-8',
    maxBuffer: SPAWN_MAX_BUFFER,
    stdio: opts.quiet ? ['inherit', 'pipe', 'pipe'] : 'inherit',
  });
  if (result.error || !(opts.ok ?? [0]).includes(result.status ?? -1)) {
    throw new Error(`command failed: ${cmd[0]}`);
  }
  return result.stdout ?? '';
}

function validateGitRef(ref: string): string {
  const trimmed = ref.trim();
  if (/^[0-9a-f]{7,40}$/i.test(trimmed)) return trimmed;
  if (/^[A-Za-z0-9._/-]+$/.test(trimmed) && !trimmed.includes('..')) return trimmed;
  throw new Error('invalid git ref');
}

/** Canonical trusted root with trailing separator (Sonar path-traversal mitigation). */
export function canonicalBaseDir(raw: string, label: string): string {
  const trimmed = raw.trim();
  if (!trimmed) throw new Error(`${label} is empty`);
  if (!isAbsolute(trimmed)) throw new Error(`${label} must be an absolute path`);
  const resolved = resolve(trimmed);
  const canonical = existsSync(resolved) ? realpathSync(resolved) : resolved;
  return canonical.endsWith(sep) ? canonical : `${canonical}${sep}`;
}

/** Resolve a path under baseDir; reject if canonical path escapes the base. */
export function pathUnderBase(baseDir: string, ...parts: string[]): string {
  const filePath = join(baseDir, ...parts);
  const canonical = existsSync(filePath) ? realpathSync(filePath) : resolve(filePath);
  if (!canonical.startsWith(baseDir)) throw new Error('Access denied');
  return canonical;
}

function paths(overlay: string, pluginsRepo: string) {
  const overlayBase = canonicalBaseDir(overlay, 'overlay-workspace');
  const pluginsBase = canonicalBaseDir(pluginsRepo, 'plugins-repo');
  const name = basename(overlayBase.slice(0, -1));
  if (!name || name === '.' || name === '..') throw new Error('invalid overlay-workspace path');

  const overlayWorkspace = overlayBase.slice(0, -1);
  const pluginsWorkspace = pathUnderBase(pluginsBase, 'workspaces', name);
  const patchPath = pathUnderBase(overlayBase, 'patches', PATCH_FILE);
  const manifestPath = pathUnderBase(overlayBase, 'patches', MANIFEST);
  const sourceJsonPath = pathUnderBase(overlayBase, 'source.json');
  const localLockPath = pathUnderBase(pluginsBase, 'workspaces', name, LOCKFILE);

  return {
    overlayWorkspace,
    pluginsRepo: pluginsBase.slice(0, -1),
    pluginsWorkspace,
    patchesDir: pathUnderBase(overlayBase, 'patches'),
    patchPath,
    manifestPath,
    sourceJsonPath,
    localLockPath,
    name,
  };
}

function readSource(sourceJsonPath: string) {
  if (!existsSync(sourceJsonPath)) throw new Error('missing source.json in overlay workspace');
  const data = JSON.parse(readFileSync(sourceJsonPath, 'utf-8')) as Json;
  const repoRef = validateGitRef(String(data['repo-ref'] ?? ''));
  return { repoRef, repoUrl: String(data.repo ?? '').trim() };
}

function readManifest(manifestPath: string): ManifestRow[] {
  if (!existsSync(manifestPath)) return [];
  const data = parseYaml(readFileSync(manifestPath, 'utf-8')) as Json;
  const rows = data.backports;
  if (rows == null) return [];
  if (!Array.isArray(rows)) throw new Error('cve-backports.yaml: backports must be a list');
  return rows as ManifestRow[];
}

export function releaseBranch(release: string): string {
  const trimmed = release.trim();
  if (!trimmed) throw new Error('release is empty');
  return trimmed.startsWith('release-') ? trimmed : `release-${trimmed}`;
}

export function validateReleaseBranch(release: string): string {
  const branch = releaseBranch(release);
  const suffix = branch.slice('release-'.length);
  if (!/^[0-9]+(\.[0-9]+)*(-[A-Za-z0-9._-]+)?$/.test(suffix)) {
    throw new Error('invalid release version');
  }
  return branch;
}

function gitRepoRoot(startPath: string): string {
  const root = exec(['git', 'rev-parse', '--show-toplevel'], { cwd: startPath, quiet: true }).trim();
  if (!root) throw new Error('not a git repository');
  return root;
}

export function resolveGitRemote(remotesListing: string, originUrl: string, canonicalRepo: string): string {
  if (/^upstream\t/m.test(remotesListing)) return 'upstream';
  if (originUrl.includes(canonicalRepo)) return 'origin';
  throw new Error('git repo has no upstream remote (fork setup)');
}

export function resolveOverlayGitRemote(remotesListing: string, originUrl: string): string {
  return resolveGitRemote(remotesListing, originUrl, OVERLAY_UPSTREAM_REPO);
}

export function resolvePluginsGitRemote(remotesListing: string, originUrl: string): string {
  return resolveGitRemote(remotesListing, originUrl, PLUGINS_UPSTREAM_REPO);
}

function gitRemote(root: string, canonicalRepo: string): string {
  const names = exec(['git', 'remote'], { cwd: root, quiet: true })
    .split('\n')
    .map(name => name.trim())
    .filter(Boolean);
  if (names.includes('upstream')) return 'upstream';
  if (names.includes('origin')) {
    const originUrl = exec(['git', 'remote', 'get-url', 'origin'], { cwd: root, quiet: true }).trim();
    if (originUrl.includes(canonicalRepo)) return 'origin';
  }
  throw new Error('git repo has no upstream remote (fork setup)');
}

function syncPluginsRepo(pluginsRepo: string, repoRef: string, dryRun?: boolean): void {
  const remote = gitRemote(pluginsRepo, PLUGINS_UPSTREAM_REPO);
  console.log(`Syncing plugins repo to ${repoRef} from ${remote}`);
  exec(['git', 'fetch', remote], { cwd: pluginsRepo, dryRun });
  exec(['git', 'fetch', remote, repoRef], { cwd: pluginsRepo, dryRun });
  exec(['git', '-c', 'advice.detachedHead=false', 'checkout', '-q', repoRef], { cwd: pluginsRepo, dryRun });
}

function fetchPluginsRef(pluginsRepo: string, repoRef: string, dryRun?: boolean): void {
  const remote = gitRemote(pluginsRepo, PLUGINS_UPSTREAM_REPO);
  exec(['git', 'fetch', remote, repoRef], { cwd: pluginsRepo, dryRun });
}

function ensureOverlayRelease(overlayWorkspace: string, release: string, opts: { dryRun?: boolean; force?: boolean }): void {
  const branch = validateReleaseBranch(release);
  const root = gitRepoRoot(overlayWorkspace);
  const remote = gitRemote(root, OVERLAY_UPSTREAM_REPO);
  const remoteRef = `${remote}/${branch}`;

  if (!opts.force && !opts.dryRun) {
    const dirty = exec(['git', 'status', '--porcelain'], { cwd: root, quiet: true });
    if (dirty) throw new Error('overlay repo has uncommitted changes; commit/stash or pass --force');
  }

  console.log(`Syncing overlay repo to ${branch} from ${remote}`);
  exec(['git', 'fetch', remote, branch], { cwd: root, dryRun: opts.dryRun });

  const current = opts.dryRun ? '' : exec(['git', 'branch', '--show-current'], { cwd: root, quiet: true }).trim();
  if (current !== branch) {
    exec(['git', 'checkout', '-B', branch, remoteRef], { cwd: root, dryRun: opts.dryRun });
  } else {
    exec(['git', 'merge', '--ff-only', remoteRef], { cwd: root, dryRun: opts.dryRun });
  }
}

function logContext(release: string, workspaceName: string) {
  console.log(`RHDH release: ${release} (${releaseBranch(release)})`);
  console.log(`workspace:     ${workspaceName}`);
}

function escPkg(pkg: string): string {
  return pkg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function sortVersions(versions: string[]): string[] {
  return [...new Set(versions.filter(Boolean))].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

export function formatPatchVersions(versions: string[]): string {
  return sortVersions(versions).join(', ');
}

export function parsePatchVersions(value: string): string[] {
  return sortVersions(value.split(',').map(v => v.trim()));
}

/** Collect every distinct version of pkg from `npm ls --json` output. */
export function collectPackageVersionsFromNpmLs(tree: unknown, pkg: string): string[] {
  const found: string[] = [];
  const walk = (node: unknown): void => {
    if (!node || typeof node !== 'object') return;
    for (const [name, dep] of Object.entries((node as Json).dependencies ?? {})) {
      if (name === pkg && dep && typeof dep === 'object') {
        const ver = String((dep as Json).version ?? '').trim();
        if (ver) found.push(ver);
      }
      walk(dep);
    }
  };
  walk(tree);
  return sortVersions(found);
}

function versionsInLock(text: string, pkg: string): string[] {
  return sortVersions([...text.matchAll(new RegExp(`resolution: "${escPkg(pkg)}@npm:([^"]+)"`, 'gm'))].map(m => m[1]));
}

export function resolveVersions(
  pkg: string,
  pluginsWorkspace: string,
  lockText: string,
  cve?: CveDetails,
  npmLsJson?: string,
): string[] {
  if (!new RegExp(`"${escPkg(pkg)}@npm:`).test(lockText)) return [];
  try {
    const raw =
      npmLsJson ??
      exec(['npm', 'ls', pkg, '--json'], { cwd: pluginsWorkspace, quiet: true, ok: [0, 1] }).trim();
    if (raw) {
      const fromTree = collectPackageVersionsFromNpmLs(JSON.parse(raw), pkg);
      if (fromTree.length) return fromTree;
    }
  } catch {
    console.error('warning: npm ls failed');
  }
  const fromLock = versionsInLock(lockText, pkg);
  if (fromLock.length) return fromLock;
  if (cve?.patch_versions.length) {
    console.error(`warning: using MITRE patch versions for ${pkg}`);
    return sortVersions(cve.patch_versions);
  }
  throw new Error('could not resolve package version');
}

/** Try each MITRE or override package name until one resolves in the lockfile (triager behavior). */
export function resolveVersionsForCve(
  cve: CveDetails,
  pluginsWorkspace: string,
  lockText: string,
): { package: string; versions: string[] } | undefined {
  for (const pkg of cve.names) {
    if (!pkg) continue;
    try {
      const versions = resolveVersions(pkg, pluginsWorkspace, lockText, cve);
      if (versions.length) return { package: pkg, versions };
    } catch {
      // try next override name
    }
  }
  return undefined;
}

export function requireLockfileChange(baseline: string, patched: string): void {
  if (baseline === patched) {
    throw new Error('yarn.lock unchanged from repo-ref baseline; bump vulnerable packages with yarn up before generate');
  }
}

function writeLockPatch(baseline: string, patched: string, patchPath: string, dryRun: boolean): void {
  requireLockfileChange(baseline, patched);
  const tmp = mkdtempSync(join(tmpdir(), 'yarnlock-backport-'));
  try {
    const a = join(tmp, 'a.lock');
    const b = join(tmp, 'b.lock');
    writeFileSync(a, baseline);
    writeFileSync(b, patched);
    const diff = spawnText('diff', ['-u', '--label', LOCKFILE, '--label', LOCKFILE, a, b]);
    if (diff.error) throw new Error('diff failed');
    if (diff.status !== 0 && diff.status !== 1) throw new Error('diff failed');
    let body = diff.stdout ?? '';
    if (!body.trim()) {
      console.log('diff produced no output; no patch written');
      return;
    }
    if (!body.endsWith('\n')) body += '\n';
    const verify = join(tmp, 'verify');
    mkdirSync(verify);
    writeFileSync(join(verify, LOCKFILE), baseline);
    const check = spawnText('patch', ['-p0', '--dry-run', '-l', '--no-backup-if-mismatch', '-f'], { cwd: verify, input: body });
    if (check.status !== 0) {
      throw new Error('generated patch failed dry-run verification');
    }
    if (dryRun) {
      console.log(`[dry-run] would write ${PATCH_FILE} (${body.length} bytes)`);
      return;
    }
    mkdirSync(dirname(patchPath), { recursive: true });
    writeFileSync(patchPath, body);
    console.log(`Wrote ${PATCH_FILE}`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

type ManifestEntry = { cveId: string; package: string; patch_versions: string[]; notes?: string };

function notesByCveId(manifestPath: string): Map<string, string> {
  const notes = new Map<string, string>();
  for (const row of readManifest(manifestPath)) {
    const text = stripAutoNotes(String(row.notes ?? '').trim());
    if (!text) continue;
    for (const id of row.cve_ids ?? []) {
      const cveId = String(id).trim();
      if (cveId) notes.set(normalizeCveId(cveId), text);
    }
  }
  return notes;
}

function manifestEntries(manifestPath: string): ManifestEntry[] {
  const entries: ManifestEntry[] = [];
  for (const row of readManifest(manifestPath)) {
    const pkg = String(row.package ?? '').trim();
    const vers = parsePatchVersions(String(row.patch_version ?? ''));
    const notes = String(row.notes ?? '').trim() || undefined;
    if (!pkg || !vers.length) continue;
    for (const id of row.cve_ids ?? []) {
      const cveId = String(id).trim();
      if (cveId) entries.push({ cveId: normalizeCveId(cveId), package: pkg, patch_versions: vers, notes });
    }
  }
  return entries;
}

export function buildManifestRows(entries: ManifestEntry[]): ManifestRow[] {
  const groups = new Map<string, ManifestRow>();
  for (const { cveId, package: pkg, patch_versions, notes } of [...entries].sort((a, b) =>
    a.cveId.localeCompare(b.cveId) || a.package.localeCompare(b.package) || formatPatchVersions(a.patch_versions).localeCompare(formatPatchVersions(b.patch_versions)),
  )) {
    const patch_version = formatPatchVersions(patch_versions);
    const key = `${pkg}\0${patch_version}`;
    const row = groups.get(key) ?? { cve_ids: [], package: pkg, patch_version };
    if (!row.cve_ids.includes(cveId)) row.cve_ids.push(cveId);
    if (notes && !row.notes) row.notes = notes;
    groups.set(key, row);
  }
  return [...groups.values()]
    .sort((a, b) => a.package.localeCompare(b.package) || a.patch_version.localeCompare(b.patch_version))
    .map(r => {
      const row: ManifestRow = { cve_ids: [...r.cve_ids].sort((a, b) => a.localeCompare(b)), package: r.package, patch_version: r.patch_version };
      if (r.notes) row.notes = r.notes;
      return row;
    });
}

function manifestRows(entries: ManifestEntry[]): ManifestRow[] {
  return buildManifestRows(entries);
}

export function formatManifestDocument(repoRef: string, rows: ManifestRow[]): string {
  return (
    MANIFEST_HEADER +
    stringifyYaml({ patch_file: PATCH_FILE, repo_ref: repoRef, backports: rows }, { lineWidth: 0 })
  );
}

async function updateManifest(opts: {
  manifestPath: string;
  repoRef: string;
  cveIds: string[];
  cveDict: Record<string, CveDetails>;
  pluginsWorkspace: string;
  lockText: string;
  dryRun: boolean;
  reportSkips?: boolean;
}) {
  const updateIds = new Set(opts.cveIds.map(id => normalizeCveId(id)));
  const preservedNotes = notesByCveId(opts.manifestPath);
  const entries = manifestEntries(opts.manifestPath).filter(e => !updateIds.has(e.cveId));

  const touched = new Set<string>();
  const skipped: string[] = [];
  for (const cveId of opts.cveIds) {
    const key = normalizeCveId(cveId);
    const cve = opts.cveDict[key];
    if (!cve?.names?.length) throw new Error('no npm package resolved for CVE');
    const resolved = resolveVersionsForCve(cve, opts.pluginsWorkspace, opts.lockText);
    if (!resolved) {
      const label = cve.names.join(', ');
      skipped.push(`${key} (${label}): not in yarn.lock`);
      if (opts.reportSkips !== false) console.error(`warning: skipping ${key} (${label}): not in yarn.lock`);
      continue;
    }
    entries.push({
      cveId: key,
      package: resolved.package,
      patch_versions: resolved.versions,
      notes: preservedNotes.get(key),
    });
    touched.add(key);
  }

  let rows = manifestRows(entries);
  const fullCveDict = await ensureCveDict([...new Set(entries.map(e => e.cveId))], opts.cveDict);
  rows = enrichManifestRowsWithVulnerabilityNotes(rows, fullCveDict, opts.pluginsWorkspace);

  if (!opts.dryRun) {
    mkdirSync(dirname(opts.manifestPath), { recursive: true });
    writeFileSync(opts.manifestPath, formatManifestDocument(opts.repoRef, rows));
    console.log(`Wrote ${MANIFEST}`);
  }

  return { touched, skipped, rows: rows.filter(r => r.cve_ids.some(id => touched.has(id))) };
}

function printReroll(workspaceName: string, bumps: string[]) {
  console.error(`\nPatch ${PATCH_FILE} failed — yarn.lock at repo-ref no longer matches the patch baseline.`);
  console.error('Re-roll: yarn up', bumps.length ? [...new Set(bumps)].join(' ') : '<packages>');
  console.error(`  in plugins workspace: ${workspaceName}`);
  console.error('  yarnlock-backport generate --release … --cve …');
}

// --- commands ---

export async function prepareWorkspace(opts: {
  release: string;
  overlayWorkspace: string;
  pluginsRepo: string;
  skipPatch?: boolean;
  force?: boolean;
  dryRun?: boolean;
}): Promise<void> {
  const ctx = paths(opts.overlayWorkspace, opts.pluginsRepo);
  ensureOverlayRelease(ctx.overlayWorkspace, opts.release, { dryRun: opts.dryRun, force: opts.force });
  const { repoRef } = readSource(ctx.sourceJsonPath);
  logContext(opts.release, ctx.name);

  if (!opts.force && !opts.dryRun && exec(['git', 'status', '--porcelain'], { cwd: ctx.pluginsRepo, quiet: true })) {
    throw new Error('plugins repo has uncommitted changes; commit/stash or pass --force');
  }

  syncPluginsRepo(ctx.pluginsRepo, repoRef, opts.dryRun);
  if (!opts.dryRun && !existsSync(ctx.pluginsWorkspace)) throw new Error('missing plugins workspace');

  console.log('Step 1a: yarn install');
  exec(['yarn', 'install'], { cwd: ctx.pluginsWorkspace, dryRun: opts.dryRun, quiet: true });

  if (opts.skipPatch) {
    console.log('Skipping patch (--skip-patch). Next: yarnlock-backport generate …');
    return;
  }

  if (!existsSync(ctx.patchPath)) {
    console.log(`No ${PATCH_FILE}; starting from repo-ref baseline`);
    return;
  }

  const patchData = readFileSync(ctx.patchPath, 'utf-8');
  const patchOpts = patchData.includes('diff --git') || patchData.includes('--- a/') ? ['-p1'] : ['-p0'];
  console.log(`Step 1b: applying ${PATCH_FILE}`);

  if (opts.dryRun) {
    exec(['patch', ...patchOpts, '--dry-run', '-l', '--no-backup-if-mismatch', '-f'], { cwd: ctx.pluginsWorkspace, input: patchData, quiet: true });
    return;
  }

  const result = spawnText('patch', [...patchOpts, '-l', '--no-backup-if-mismatch', '-f'], { cwd: ctx.pluginsWorkspace, input: patchData });
  if (result.status !== 0) {
    const bumps: string[] = [];
    for (const row of readManifest(ctx.manifestPath)) {
      const pkg = String(row.package ?? '').trim();
      for (const ver of parsePatchVersions(String(row.patch_version ?? ''))) {
        if (pkg && ver) bumps.push(`${pkg}@${ver}`);
      }
    }
    printReroll(ctx.name, bumps);
    throw new Error(`failed to apply ${PATCH_FILE}`);
  }
  console.log('Patch applied. Next: yarnlock-backport generate …');
}

export async function generateBackport(opts: {
  release: string;
  overlayWorkspace: string;
  pluginsRepo: string;
  cve: string;
  dryRun?: boolean;
}): Promise<void> {
  const ctx = paths(opts.overlayWorkspace, opts.pluginsRepo);
  ensureOverlayRelease(ctx.overlayWorkspace, opts.release, { dryRun: opts.dryRun });
  const { repoRef } = readSource(ctx.sourceJsonPath);
  logContext(opts.release, ctx.name);

  if (!existsSync(ctx.localLockPath)) throw new Error(`missing local ${LOCKFILE}`);
  if (!opts.dryRun && !existsSync(ctx.pluginsWorkspace)) throw new Error('missing plugins workspace');

  console.log('yarn install');
  exec(['yarn', 'install'], { cwd: ctx.pluginsWorkspace, dryRun: opts.dryRun, quiet: true });

  fetchPluginsRef(ctx.pluginsRepo, repoRef, opts.dryRun);
  const baseline = exec(['git', 'show', `${repoRef}:workspaces/${ctx.name}/${LOCKFILE}`], { cwd: ctx.pluginsRepo, quiet: true });
  const patched = readFileSync(ctx.localLockPath, 'utf-8');
  if (!opts.dryRun) requireLockfileChange(baseline, patched);

  const tokens = parseCveArg(opts.cve);
  const cveDict = await fetchAllCveDetails(tokens);
  const cveIds = tokens.map(t => parseCveCliToken(t)[0]);

  let { touched, skipped, rows } = await updateManifest({
    manifestPath: ctx.manifestPath,
    repoRef,
    cveIds,
    cveDict,
    pluginsWorkspace: ctx.pluginsWorkspace,
    lockText: patched,
    dryRun: true,
  });
  if (!touched.size && skipped.length) throw new Error('no CVE packages from --cve are present in this workspace yarn.lock');

  writeLockPatch(baseline, patched, ctx.patchPath, opts.dryRun ?? false);
  if (!opts.dryRun) {
    ({ rows, skipped } = await updateManifest({
      manifestPath: ctx.manifestPath,
      repoRef,
      cveIds,
      cveDict,
      pluginsWorkspace: ctx.pluginsWorkspace,
      lockText: patched,
      dryRun: false,
      reportSkips: false,
    }));
  }

  if (rows.length) {
    console.log(`\n${opts.dryRun ? '[dry-run] ' : ''}Recorded ${rows.length} manifest row(s)`);
  }
  if (skipped.length) {
    console.log(`Skipped ${skipped.length} CVE entries not in yarn.lock`);
  }
}
