apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: rhdh
  name: packages
spec:
  targets:
    - ./backstage-community-plugin-quay-backend.yaml
    - ./backstage-community-plugin-quay.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-quay.yaml
    - ./backstage-community-plugin-tekton.yaml
    - ./rhdh-bsp-ctlg-backend-mod-extensions.yaml
    - ./roadiehq-backstage-plugin-argo-cd-backend.yaml
    - ./roadiehq-scaffolder-backend-argocd.yaml
