apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-signals-backend
  namespace: rhdh
  title: "Signals Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/signals-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/signals-backend
  tags: []
spec:
  packageName: "@backstage/plugin-signals-backend"
  # Tag: bs_1.54.9__0.3.18, Build date: 2026-05-21T21:25:10Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-signals-backend@sha256:06c8327062e9ede0f4882562e1c9a536bf40e3f8eb28923dc4e0dab98bba5c04"
  version: 0.3.18
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.9
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - signals-frontend
    - signals-backend
  appConfigNotRequired: true
  appConfigExamples: []
