apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-regex
  namespace: rhdh
  title: "Scaffolder Backend Module Regex"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-regex
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-regex
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-regex"
  # Tag: bs_1.54.4__2.18.0, Build date: 2026-05-26T12:36:49Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-scaffolder-backend-module-regex@sha256:1522ce5c418763b0a29c7c61cc04c41c1f40f1ae85b24af4cc0e3bf017970fb4"
  version: 2.18.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - regex-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
