apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-gitlab
  namespace: rhdh
  title: "Scaffolder Backend Module GitLab"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/gitlab
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/gitlab
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-gitlab"
  # Tag: bs_1.54.6__0.11.10, Build date: 2026-05-21T21:20:59Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-scaffolder-backend-module-gitlab@sha256:fd711d4d1cc1cda91e691996b7e2c33e1a4b3cbf8c76accb6593c2274e25f19d"
  version: 0.11.10
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - gitlab-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
