apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-org
  namespace: rhdh
  title: "Org"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/org
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/org
  tags: []
spec:
  packageName: "@backstage/plugin-org"
  # Tag: bs_1.54.9__0.7.8
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-org@sha256:f236e2eac7ec1bb9660f09b56b0fb42d2f9067147297218af25d511ee4f17819"
  version: 0.7.8
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - org
  appConfigNotRequired: true
  appConfigExamples: []
