apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-techdocs-backend
  namespace: rhdh
  title: "TechDocs Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend
  tags: []
spec:
  packageName: "@backstage/plugin-techdocs-backend"
  # Tag: bs_1.54.6__2.2.4, Build date: 2026-05-21T21:24:29Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-techdocs-backend@sha256:ec34f0d1ec5808c66dc8a5a74501d099d20e4c2cacd1c85e0d17b6a44ff124f4"
  version: 2.2.4
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - techdocs
  appConfigExamples:
    - title: Default configuration
      content:
        techdocs:
          builder: local
          generator:
            runIn: local
          publisher:
            type: local
