apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-kubernetes-backend
  namespace: rhdh
  title: "Kubernetes Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/kubernetes-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/kubernetes-backend
  tags: []
spec:
  packageName: "@backstage/plugin-kubernetes-backend"
  # Tag: bs_1.54.9__0.21.10
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-kubernetes-backend@sha256:5170f2fe3e9b409aea53cdf4bae3d2bf7e9fc643d586ecc7fdcbcc040fbf1b18"
  version: 0.21.10
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.9
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - kubernetes
  appConfigExamples:
    - title: Default configuration
      content:
        kubernetes:
          serviceLocatorMethod:
            type: multiTenant
          clusterLocatorMethods:
            - type: config
              clusters:
                - name: ${K8S_CLUSTER_NAME}
                  url: ${K8S_CLUSTER_URL}
                  authProvider: serviceAccount
                  skipTLSVerify: true
                  serviceAccountToken: ${K8S_CLUSTER_TOKEN}
