apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator-backend-module-loki
  namespace: rhdh
  title: "Orchestrator Backend Module Loki"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-backend-module-loki
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-backend-module-loki
  tags:
    - automation
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-orchestrator-backend-module-loki"
  # Tag: bs_1.49.4__1.2.7
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-orchestrator-backend-module-loki@sha256:3866b169038f0fdedeb2a0a54007880c2a6db60a86c534f730bb7883fe639a08"
  version: 1.2.7
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - orchestrator
  appConfigExamples:
    - title: Default configuration
      content:
        orchestrator:
          workflowLogProvider:
            loki:
              baseUrl: ${LOKI_BASE_URL}
              token: ${AUTH_TOKEN}
