apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-scorecard-backend-mod-code-coverage
  namespace: rhdh
  title: "Scorecard Backend Module for Code Coverage"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-code-coverage
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-code-coverage
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-code-coverage"
  # Tag: bs_1.54.9__0.1.4
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-code-coverage@sha256:e843a4fd110a406ab80623140f8de80848cf0ddad67c1b9a1acffb6c624f0e40"
  version: 0.1.4
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.9
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigNotRequired: true
  appConfigExamples: []
