apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-scorecard-backend-mod-openssf
  namespace: rhdh
  title: "Scorecard Backend Module for OpenSSF Security Scorecards"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-openssf
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-openssf
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-openssf"
  # Tag: bs_1.54.9__2.0.1
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-openssf@sha256:0ab2f2429a19f98ae52f9d9e3087284bcf0b5f7dd0c96947afa68594391ebe28"
  version: 2.0.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.9
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigNotRequired: true
  appConfigExamples: []
