apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-adoption-insights-backend
  namespace: rhdh
  title: "Adoption Insights Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/adoption-insights
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/adoption-insights
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-adoption-insights-backend"
  # Tag: bs_1.49.4__0.8.3, Build date: 2026-05-22T15:13:50Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-adoption-insights-backend@sha256:46d6e98b9572cd4a9294e07e3a54403e437402b3d982ea4b92060734698c28c8"
  version: 0.8.3
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - adoption-insights
  appConfigExamples:
    - title: Default configuration
      content:
        app:
          analytics:
            adoptionInsights:
              maxBufferSize: 20
              flushInterval: 5000
              debug: false
              licensedUsers: 100
