apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-search-backend-module-adr
  namespace: rhdh
  title: "Search Backend Module Adr"
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://github.com/backstage/community-plugins/issues
    title: Bugs
  - title: Source Code
    url: https://github.com/backstage/community-plugins/tree/main/workspaces/adr
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/adr
  tags: []
spec:
  packageName: '@backstage-community/search-backend-module-adr'
  dynamicArtifact: oci://ghcr.io/veecode-platform/devportal-plugin-export-overlays/backstage-community-search-backend-module-adr:bs_1.48.4__0.13.1!backstage-community-search-backend-module-adr
  version: 0.13.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.48.4
  author: VeeCode
  support: community
  lifecycle: active
  partOf:
  - adr
