apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-redhat-argocd-backend
  namespace: rhdh
  title: "Red Hat ArgoCD Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-backend-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-backend-dynamic
  tags: []
spec:
  packageName: "@backstage-community/plugin-redhat-argocd-backend"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd-backend-dynamic
  version: 2.0.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - redhat-argocd
  appConfigExamples:
    - title: Default configuration
      content:
        argocd:
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}
          appLocatorMethods:
            - type: config
              instances:
                - name: argoInstance1
                  url: ${ARGOCD_INSTANCE1_URL}
                  token: ${ARGOCD_AUTH_TOKEN}

