apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-servicenow
  namespace: rhdh
  title: "Scaffolder Backend Module ServiceNow"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-servicenow
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-servicenow
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-servicenow"
  # Tag: 1.9.0--2.11.0, Build date: 2026-01-29T16:28:59Z
  dynamicArtifact: "oci://registry.access.redhat.com/rhdh/backstage-community-plugin-scaffolder-backend-module-servicenow@sha256:3ff2122f96463ec0a9c4cfee71e4be0333b8cd82e086c9433c8c9c3a45ac3eb5"
  version: 2.11.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - servicenow-scaffolder-actions
  appConfigExamples:
    - title: Default configuration
      content:
        servicenow:
          baseUrl: ${SERVICENOW_BASE_URL}
          username: ${SERVICENOW_USERNAME}
          password: ${SERVICENOW_PASSWORD}
