apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-sonarqube-backend
  namespace: rhdh
  title: "SonarQube Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/sonarqube
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/sonarqube
  tags: []
spec:
  packageName: "@backstage-community/plugin-sonarqube-backend"
  # Tag: bs_1.54.6__1.2.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-sonarqube-backend@sha256:dfc27b81225db1bdcdb1bcd1386f210382b32f9aaa94ac80cbcb0f324f6dbab4"
  version: 1.2.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - sonarqube-catalog-cards
  appConfigExamples:
    - title: Default configuration
      content:
        sonarqube:
          baseUrl: ${SONARQUBE_URL}
          apiKey: ${SONARQUBE_TOKEN}
