apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-azure-devops-backend
  namespace: rhdh
  title: "Azure DevOps Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops
  tags: []
spec:
  packageName: "@backstage-community/plugin-azure-devops-backend"
  # Tag: bs_1.54.9__0.32.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-azure-devops-backend@sha256:e14b3f5586d2778a3e00d064ba72e83225619d6ece3a30d1a7e883e5ec0032e1"
  version: 0.32.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - azure-devops
  appConfigExamples:
    - title: Default configuration
      content:
        azureDevOps:
          host: dev.azure.com
          token: ${AZURE_TOKEN}
          organization: ${AZURE_ORG}
          pullRequestDashboard:
            organizations:
              - organization: ${AZURE_ORG}
                host: ${AZURE_HOST}
