apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-gerrit
  namespace: rhdh
  title: "Scaffolder Backend Module Gerrit"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-gerrit
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-gerrit
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-gerrit"
  # Tag: bs_1.54.6__0.2.24
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-scaffolder-backend-module-gerrit@sha256:8c0b3adfc0127917eb542ecce91c453b8210fe4ea211d38cb05068dc7535abc6"
  version: 0.2.24
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - gerrit-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
