apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-dynatrace
  namespace: rhdh
  title: "Dynatrace"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/dynatrace
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/dynatrace
  tags: []
spec:
  packageName: "@backstage-community/plugin-dynatrace"
  # Tag: bs_1.54.6__10.23.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-dynatrace@sha256:2a85d556257779ea127fbaf64e09d34a224e5e29a4f464670cbc693cdb04bfd3"
  version: 10.23.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Dynatrace
  support: community
  lifecycle: active
  partOf:
    - dynatrace-community
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-dynatrace:
              mountPoints:
                - mountPoint: entity.page.monitoring/cards
                  importName: DynatraceTab
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isDynatraceAvailable
