apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-jenkins
  namespace: rhdh
  title: "Jenkins Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  tags: []
spec:
  packageName: "@backstage-community/plugin-jenkins"
  # Tag: bs_1.54.6__0.34.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-jenkins@sha256:b3634ce85529c781160453acd3e3cd8839e2b64d8eca08129f6beb4dc0b7786c"
  version: 0.34.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - jenkins
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-jenkins:
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: EntityJenkinsContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isJenkinsAvailable
