apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-gerrit
  namespace: rhdh
  title: "Scaffolder Backend Module Gerrit"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-gerrit
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-gerrit
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-gerrit"
  # Tag: bs_1.52.0__0.2.22
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-scaffolder-backend-module-gerrit@sha256:680e8687c5421aa818805443d02914f2d6c51045a9812858d72e6b9dd5e6d5a1"
  version: 0.2.22
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - gerrit-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
