apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-utils
  namespace: rhdh
  title: "Scaffolder Backend Module Utils"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-utils"
  # Tag: bs_1.54.9__4.2.1
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-scaffolder-backend-module-utils@sha256:38581109c5f9b11509a5a5bdd72681505da3c9d15343a5a5271fc4ba8eedcd1c"
  version: 4.2.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Roadie
  support: community
  lifecycle: active
  partOf:
    - roadie-scaffolder-util-actions
  appConfigNotRequired: true
  appConfigExamples: []
