#!/usr/bin/env bash
#
# Seed committed per-workspace coverage snapshots onto the current default-branch
# (main) commit, so the Codecov default-branch view shows data for the
# workspaces already rolled out.
#
# Why this exists:
#   E2E coverage is only generated by the Prow e2e jobs, which deploy
#   INSTRUMENTED plugin images — and those images are only built by the PR
#   /publish flow (auto-publish-pr.yaml). So coverage is always uploaded
#   against a PR-head commit. When the PR is squash-merged, GitHub creates a
#   brand-new commit on main that never received an upload, and Codecov's
#   carryforward can't reach across the squash (the PR head is not an ancestor
#   of the squash commit). The result: every flag reads empty on main except
#   ones seeded by hand.
#
#   This script re-attributes the latest captured snapshot of each workspace's
#   coverage to the current main commit (scripts/upload-coverage.sh resolves
#   the SHA from GITHUB_SHA and the branch to main). It runs from
#   .github/workflows/seed-coverage-main.yaml on a schedule and whenever a
#   snapshot changes on main.
#
#   This is a bridge. The snapshot is a point-in-time capture (committed under
#   coverage-snapshots/<workspace>.lcov, refreshed by scripts/refresh-coverage-
#   snapshot.sh when a workspace's e2e runs), so the number only changes when
#   the snapshot is refreshed — which is also the only time the coverage itself
#   changes. The long-term replacement is live coverage from a main-attributed
#   Prow run (needs instrumented release images + an e2e-test-utils nightly
#   swap); see the repo README.
#
# Required environment:
#   CODECOV_TOKEN  - Codecov upload token (forwarded to upload-coverage.sh).
#   GITHUB_SHA     - Set by GitHub Actions to the default-branch HEAD.
#
# Optional environment:
#   SEED_SKIP_IF_ALREADY_SEEDED - "true" to no-op when the target commit already
#                    carries every workspace this would upload. Set only for the
#                    scheduled backstop; see the rationale at the check below.

set -euo pipefail

# Without a token, upload-coverage.sh warns and exits 0 for every workspace, so
# the job would go green while uploading nothing. Fail fast on the
# misconfiguration instead — for this upload-only job a missing token is a red X.
# (CODECOV_UPLOAD_STRICT below closes the same hole for a failed upload.)
if [[ -z "${CODECOV_TOKEN:-}" && -z "${VAULT_CODECOV_TOKEN:-}" ]]; then
  echo "ERROR: no Codecov token (CODECOV_TOKEN / VAULT_CODECOV_TOKEN) — the seed would upload nothing. Set the CODECOV_TOKEN secret." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SNAPSHOT_DIR="$REPO_ROOT/coverage-snapshots"

shopt -s nullglob
snapshots=("$SNAPSHOT_DIR"/*.lcov)
shopt -u nullglob

if [[ ${#snapshots[@]} -eq 0 ]]; then
  echo "[INFO] No coverage snapshots in $SNAPSHOT_DIR — nothing to seed."
  exit 0
fi

WORKSPACES=()
for snapshot in "${snapshots[@]}"; do
  WORKSPACES+=("$(basename "$snapshot" .lcov)")
done

SEED_SHA="${GITHUB_SHA:-$(git -C "$REPO_ROOT" rev-parse HEAD)}"

# Same default as upload-coverage.sh, split because the Codecov API path puts the
# owner and the repo in different segments.
SEED_SLUG="${CODECOV_UPLOAD_SLUG:-redhat-developer/rhdh-plugin-export-overlays}"
SEED_OWNER="${SEED_SLUG%%/*}"
SEED_REPO="${SEED_SLUG##*/}"

# Codecov APPENDS an upload session per upload — re-seeding a commit that already
# carries the data does not replace those sessions. Measured on this repo:
# 129f9ac5 was seeded by the schedule on two consecutive days with 6 snapshots
# each and carries 12 sessions, against 6 for fc27ff56 (seeded once, 6 snapshots)
# — identical 49.27% coverage either way. So the number stays right but the
# sessions grow without bound on a main HEAD that nothing has moved, and a 6h
# schedule accumulates 4x faster than a daily one did.
#
# Hence: the scheduled backstop skips a commit that already carries every
# workspace it would upload. Push and manual dispatch never set this — "re-run
# the workflow" has to stay the fix for a stale flag.
#
# Returns 0 (skip) only on a positive answer. Any doubt — API down, jq missing,
# report still processing, one workspace absent — falls through to uploading,
# because a redundant upload is cheap and a skipped one strands a flag.
already_fully_seeded() {
  local json have ws
  command -v jq >/dev/null 2>&1 || return 1
  json="$(curl -sf --max-time 30 \
    "https://api.codecov.io/api/v2/github/${SEED_OWNER}/repos/${SEED_REPO}/commits/${SEED_SHA}/")" || return 1
  [[ "$(jq -r '.state // empty' <<<"$json")" == "complete" ]] || return 1

  # Every anchor path is workspaces/<ws>/coverage-anchors/<plugin>, so the set of
  # workspaces already on the commit falls out of the report's file list.
  have="$(jq -r '.report.files[]?.name' <<<"$json" |
    sed -n 's#^workspaces/\([^/]*\)/coverage-anchors/.*#\1#p' | sort -u)"
  for ws in "${WORKSPACES[@]}"; do
    grep -qxF "$ws" <<<"$have" || return 1
  done
  return 0
}

if [[ "${SEED_SKIP_IF_ALREADY_SEEDED:-false}" == "true" ]]; then
  if already_fully_seeded; then
    echo "[INFO] ${SEED_SHA:0:8} already carries all ${#WORKSPACES[@]} workspace(s) — skipping to avoid piling up duplicate Codecov sessions."
    exit 0
  fi
  echo "[INFO] ${SEED_SHA:0:8} is missing coverage for at least one workspace — seeding."
fi

echo "=== Seeding ${#snapshots[@]} coverage snapshot(s) to the current main commit ==="
# Declared empty so `${#FAILED_WS[@]}` is safe under `set -u` when nothing fails.
FAILED_WS=()
for snapshot in "${snapshots[@]}"; do
  # The snapshot basename must equal a workspaces/<dir> name — it becomes the
  # Codecov flag (e2e-<ws>) and upload-coverage.sh validates the directory.
  ws="$(basename "$snapshot" .lcov)"
  echo ""
  echo "--- $ws (e2e-$ws) ---"
  # Uploading IS this job — a Codecov-side failure is a real failure here, not the
  # incidental side-effect it is for a caller that also does something else. Without
  # strict, upload-coverage.sh returns 0 on a failed upload and every snapshot
  # reports as seeded while Codecov received nothing. Set per call rather than
  # exported so the scope is visible right where it applies.
  if ! CODECOV_UPLOAD_STRICT=true "$SCRIPT_DIR/upload-coverage.sh" "$ws" "$snapshot"; then
    echo "[ERROR] Seed failed for $ws"
    FAILED_WS+=("$ws")
  fi
done

FAILED="${#FAILED_WS[@]}"
echo ""
echo "=== Done: $(( ${#snapshots[@]} - FAILED ))/${#snapshots[@]} seeded ==="
# A green run here means "dashboard updated" — so ANY failed seed is a red X, not
# just an all-fail. Each workspace is an independent flag: 6/7 green would leave
# the 7th showing a stale carried-forward number with nothing to indicate it was
# never refreshed, which is precisely the silent staleness this job exists to
# prevent. The seed is idempotent and re-runs on schedule, so a re-run is the fix.
if [[ "$FAILED" -gt 0 ]]; then
  echo "[ERROR] Not seeded: ${FAILED_WS[*]}" >&2
  exit 1
fi
exit 0
