apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: proberaum-backstage-plugin-github-notifications-backend
  namespace: rhdh
  title: "Github Notifications Backend"
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://github.com/proberaum/backstage-plugins/issues
    title: Bugs
  - title: Source Code
    url: https://github.com/proberaum/backstage-plugins/tree/main/workspaces/github-notifications
  annotations:
    backstage.io/source-location: url:https://github.com/proberaum/backstage-plugins/tree/main/workspaces/github-notifications
  tags: []
spec:
  packageName: '@proberaum/backstage-plugin-github-notifications-backend'
  dynamicArtifact: oci://quay.io/veecode/github-notifications:bs_1.48.4!proberaum-backstage-plugin-github-notifications-backend
  version: 0.11.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.48.4
  author: VeeCode
  support: community
  lifecycle: active
  partOf:
  - github-notifications
