name: Publish DevPortal Dynamic Plugin Images
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'workspaces/**'
      - 'versions.json'

jobs:
  export:
    uses: veecode-platform/devportal-plugin-export-overlays/.github/workflows/publish-release-branch-workspace-plugins.yaml@main
    secrets:
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
